### PR TITLE
Changed 'NavCoin' to 'Navcoin'

### PR DESCRIPTION
**Pull request by mxaddict**
Note: Did not change the capitalization on the datadir names as that would cause users to have to move the datadir after the upgrade.

### CODE REVIEW

**Comment by aguycalled** [comment]
i see there are still more references to `NavCoin` in the code which havent been changed in this PR

**Comment by mxaddict** [comment]
> i see there are still more references to `NavCoin` in the code which havent been changed in this PR

Should be fixed now.

**Comment by navbuilder** [comment]
A new build of b3e32d8a88033a3a223555fad93ebc31b49bbfb4 has completed succesfully!
Binaries available at https://build.nav.community/binaries/changed-navcoin-capitalization

**Review by chasingkirkjufell — APPROVED** [review]
Tested gitian build on Windows 10. Wallet launched normally.

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
