### PR TITLE
Use of the CoinsDB for the Community Fund

### PR DESCRIPTION
**Pull request by aguycalled**
This PR introduces the use of the CoinsDB for the Community Fund, increasing the overall performance and preventing some consistency issues.

### CODE REVIEW

**Comment by aguycalled** [comment]
Things that can be tested:
- Comparation of speed sync
- Migration from old DBs
- Confirm CFund tests pass and all the scenarios are covered

**Comment by mxaddict** [comment]
@aguycalled I'll be testing the upgrade scenarios in a bit, but doing a testnet/devnet fresh genesis block + staking seems to be working

I will also be testing proposals and payment requests on devnet/testnet

As for the older wallets, what kind of issue might happen if we say upgrade bootstrap server (To use this new unified DB) and an older client bootstraps from that?

**Comment by mxaddict** [comment]
Also, should we keep libbdb on 4.x? Since this will break backward compatibility, maybe we should upgrade bdb to 5.x as well?

**Comment by aguycalled** [comment]
> Also, should we keep libbdb on 4.x? Since this will break backward compatibility, maybe we should upgrade bdb to 5.x as well?
> 
> Hmm, on seconds thought upgrade of BDB would also break wallet back compat.

yep, that would break wallet compat

**Comment by aguycalled** [comment]
> @aguycalled I'll be testing the upgrade scenarios in a bit, but doing a testnet/devnet fresh genesis block + staking seems to be working
> 
> I will also be testing proposals and payment requests on devnet/testnet
> 
> As for the older wallets, what kind of issue might happen if we say upgrade bootstrap server (To use this new unified DB) and an older client bootstraps from that?

Their CFund DB would be empty so they would eventually fork as soon as they see some activity on unknown proposals/payment requests. There should be two different bootstraps depending on the version.

A nice feature which would deserve a bounty is adding some kind of sanity check (version in this case) when a bootstrap is downloaded.

**Comment by mxaddict** [comment]
@aguycalled maybe a new bootstrap URL would be better?

Keep the current bootstrap URL on 4.6.0 (Atleast until we get majority of the network on the version which will eventually contain this version with the cfund update)

Then just add a new bootstrap generator for a new URL with a suffix like:

```
https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_mainnet_unified_db.tar
```

**Comment by mxaddict** [comment]
So they can keep bootstrapping on the current bootstrap URL for old clients 

And new version would just use that new URL :+1:

**Comment by mxaddict** [comment]
You would just need to change this:

```cpp
    QString defaultUrl = "https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_" +
            QString::fromStdString(Params().NetworkIDString()) + "net.tar";
```

 to this:
```cpp
    QString defaultUrl = "https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_" +
            QString::fromStdString(Params().NetworkIDString()) + "net_unified_db.tar";
```

**Comment by aguycalled** [comment]
> You would just need to change this:
> 
> ```c++
>     QString defaultUrl = "https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_" +
>             QString::fromStdString(Params().NetworkIDString()) + "net.tar";
> ```
> 
> to this:
> 
> ```c++
>     QString defaultUrl = "https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_" +
>             QString::fromStdString(Params().NetworkIDString()) + "net_unified_db.tar";
> ```

Sometimes the bootstrap url is provided by third parties. Default url must be updated, but I think it should also be checked.

**Comment by mxaddict** [comment]
> > You would just need to change this:
> > ```c++
> >     QString defaultUrl = "https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_" +
> >             QString::fromStdString(Params().NetworkIDString()) + "net.tar";
> > ```
> > 
> > 
> > to this:
> > ```c++
> >     QString defaultUrl = "https://s3.amazonaws.com/navcoin-bootstrap/bootstrap-navcoin_" +
> >             QString::fromStdString(Params().NetworkIDString()) + "net_unified_db.tar";
> > ```
> 
> Sometimes the bootstrap url is provided by third parties. Default url must be updated, but I think it should also be checked.

yeah, but we can't add that feature to the old clients though? 

And the new client will work with both old and new bootstraps, so I don't see the point in adding it?

Or am I missing something?

**Comment by mxaddict** [comment]
Basically <= 4.6.0 will not be able to use new version (And we can't add code to check) since they are already running this release

**Comment by aguycalled** [comment]
> Basically <= 4.6.0 will not be able to use new version (And we can't add code to check) since they are already running this release

yep, i meant as a sanity check for the future

**Comment by mxaddict** [comment]
> > Basically <= 4.6.0 will not be able to use new version (And we can't add code to check) since they are already running this release
> 
> yep, i meant as a sanity check for the future

I see, what kind of checks do you think would be needed?

**Comment by aguycalled** [comment]
Lets move that conversation here https://github.com/navcoin/navcoin-core/issues/488

**Comment by mxaddict** [comment]
Compiled, now testing with various datadir scenarios

**Comment by mxaddict** [comment]
Tested with bootstrap and worked fine, add proposals and payment requests over to coinsdb and removed from the pblocktree successfully locally on Ubuntu 18.04

As for the sanity checks you wanted @aguycalled, don't you think these are fine already?

https://github.com/aguycalled/navcoin-core/blob/ab5fce9af6a63ff1a3b30f34e3df6ff75f3cb717/src/init.cpp#L1654-L1694

**Comment by aguycalled** [comment]
i've also tried randomly killing the process and restarting checking the state was correctly preserved/reconstructed

**Comment by mxaddict** [comment]
> i've also tried randomly killing the process and restarting checking the state was correctly preserved/reconstructed

I think this would not be an issue, since it does not remove from the cfund copy until it's done adding.

So if it dies in middle of adding, it would just reattempt adding the next init and (And from what I can see, it will filter out dups anyway)

So I think that's not an issue.

**Comment by mxaddict** [comment]
Can confirm that test suite passes on my local build (Ubuntu 18.04)

**Comment by mxaddict** [comment]
```bash
#!/bin/bash

export TIME1=$[ ( $RANDOM % 10 )  + 1 ]s
echo "SLEEPING $TIME1"
sleep $TIME1
kill -9 `cat ~/.navcoin4/testnet3/navcoin.pid`
export TIME1=$[ ( $RANDOM % 10 )  + 1 ]s
echo "SLEEPING $TIME1"
sleep $TIME1
~/navcoind -testnet
```

I'm running this in a crontab now to make sure that issue #481 no longer occurs

**Comment by mxaddict** [comment]
@aguycalled were you able to see anything in the log file I sent reagarding this PR?

**Comment by aguycalled** [comment]
yes, it's probably related.

```
2019-05-20 21:40:59 ERROR: CheckBlock() : coinbase strdzeel refers wrong payment request hash.
2019-05-20 21:40:59 InvalidChainFound: invalid block=020e0d5e2728926fd45020818fb7f0318d450a81e09636faa308fc4d8ffc193c  height=3145011  log2_work=72.969775  date=2019-05-20 11:35:28
```

**Comment by mxaddict** [comment]
> yes, it's probably related.
> 
> ```
> 2019-05-20 21:40:59 ERROR: CheckBlock() : coinbase strdzeel refers wrong payment request hash.
> 2019-05-20 21:40:59 InvalidChainFound: invalid block=020e0d5e2728926fd45020818fb7f0318d450a81e09636faa308fc4d8ffc193c  height=3145011  log2_work=72.969775  date=2019-05-20 11:35:28
> ```

Does this need additional code changes? Or should I continue review of current PR?

**Comment by aguycalled** [comment]
> > yes, it's probably related.
> > ```
> > 2019-05-20 21:40:59 ERROR: CheckBlock() : coinbase strdzeel refers wrong payment request hash.
> > 2019-05-20 21:40:59 InvalidChainFound: invalid block=020e0d5e2728926fd45020818fb7f0318d450a81e09636faa308fc4d8ffc193c  height=3145011  log2_work=72.969775  date=2019-05-20 11:35:28
> > ```
> 
> Does this need additional code changes? Or should I continue review of current PR?



> Tested this thoroughly on Ubuntu 18.04
> 
> Only issue I could get to break was force killing the navcoind process repeatedly (Every 20-30 minutes) until it forked.
> 
> I think these changes are good to go.

Does this mean you were able to reproduce the issue?

**Comment by mxaddict** [comment]
No, it only happened once, and I had the node running until now, still fine.

**Comment by mxaddict** [comment]
I mean I had it running with the CRON that killed it randomly.

**Comment by craigmacgregor** [comment]
compiled using gitian docker on OSX. I have some weird graphics bug where the buttons are appearing pink. I will post a screen shot once the wallet opens up again. I am running the --reindex flag and will see if everything works.

Does running --reindex force the migration to occur? or how does this work?

**Comment by mxaddict** [comment]
From my testing migration runs when wallet is opened and cfunddb is not
empty.

>

**Comment by proletesseract** [comment]
--reindex flag worked. the whole chain loaded with no problems.

**Comment by proletesseract** [comment]
seems like you guys have pretty thoroughly looked at this already. Is there anything specific i should be testing on this?

**Comment by mxaddict** [comment]
@aguycalled @proletesseract I've had a node with this PR's code running for a good week now, still working fine and also staking.

**Comment by mxaddict** [comment]
@aguycalled, maybe update this branch with latest commits from master branch?

Or rebase :+1:

**Comment by proletesseract** [comment]
im going to compile in linux and run the test suite then ill be happy to approve/merge once travis works again

**Comment by proletesseract** [comment]
restarting travis to see if it passes and I'll merge this if it does. I can build on ubuntu and the rpc-tests all pass. I can build with gitian and the OSX build was able to reindex correctly and function nominally.

**Pull request merged**
