### PR TITLE
Updated depends to use winssl for windows and darwinssl for osx

### LINKED ISSUE #594: Most currencies in the drop down menu aren't working
### Description
In the 4.7.0 release candidate (tested on OSX) only the original currencies of NAV, BTC, EUR and USD populate correctly. The other currencies beginning from ARS all show 0.00000 amounts in Balances, Staking and Transactions.

### Motivation
Having the above fields populated with the proper amounts gives users more confidence that the wallet is working correctly.

Screenshot at Aug 27 23-28-35

### Acceptance Criteria

Add any additional acceptance criteria you think should be included to the list below.

- [ ] Description is satisfied.
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or ammended as necessary.

### PR DESCRIPTION
**Pull request by mxaddict**
closes #594
closes #591

### CODE REVIEW

**Comment by mxaddict** [comment]
I've tested and is working with windows gitian build.

Will test with OSX gitian build once I get hands on a mac.

**Comment by mxaddict** [comment]
I've tested this build on OSX 10.14, and currencies won't load, but working on windows, I'm checking to see why.

**Comment by mxaddict** [comment]
I've found the reason for the OSX curl not getting the right certs and am working with the curl devs here: https://github.com/curl/curl/issues/4312

**Comment by mxaddict** [comment]
Binaries with patched curl:
http://static.codedmaster.com/nstake/navcoin-4.7.0-win32-setup-unsigned.exe
http://static.codedmaster.com/nstake/navcoin-4.7.0-win64-setup-unsigned.exe
http://static.codedmaster.com/nstake/navcoin-4.7.0-osx-unsigned.dmg

**Comment by magpie17** [comment]
tested new build from @mxaddict from this address - http://static.codedmaster.com/nstake/navcoin-4.7.0-osx-unsigned.dmg and I was able to confirm that the price I was having (no prices or amounts showing when choosing any currency after USD in the drop down list) has been resolved. Attached image is proof that I can now see amounts in a different currency (i.e. NZD) when looking at the Transactions section of the core wallet.
unknown

**Comment by proletesseract** [comment]
Tested on 64bit Windows 10 virtual box. I don't have balance (and am not synced) on the VM though. Should i see (or not see) something in the logs if it's working correctly?

**Comment by mxaddict** [comment]
> I ran the wallet successfully on;
> 
> * 64bit Windows 10 virtual box.
> * 32bit Windows 8.1 virtual box.
> * MacOS High Sierra on a Mac mini.
> 
> I don't have balance (and am not fully synced yet) so not sure how to tell if it's working? I can switch currencies in the drop down and I don't see any errors appear on the `Debug Window > Error Log`. Should i see (or not see) something in the logs if it's working correctly?

There should be entries in the debug.log that state a successful price update should look like this: `[INFO] Updated prices`

**Comment by proletesseract** [comment]
Can confirm i see the info logs in Windows64 and MacOS. Turns out the Windows 8.1 box i thought was 32bit was actually 64bit. Is it enough to run the 32bit version in 64bit OS?

**Comment by proletesseract** [comment]
Can confirm i see the info logs in Windows64 running the 32bit binary.

**Pull request merged**
