### PR TITLE
Only broadcast xnav when received version

### PR DESCRIPTION
**Pull request by aguycalled**
This PR fixes a bug which banned peers who broadcasted aggregation sessions and encrypted candidates before completing the handshake.

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 39ef8d19922ef4437d57f5676680d3aae88655f3 has completed succesfully!
Binaries available at https://build.nav.community/binaries/broadcast_after_version

**Comment by chasingkirkjufell** [comment]
aggregation sessions are collecting candidates fine, but i see this message when trying to send mixed coins

2021-04-14 18:25:30 ERROR: AggregationSession::SelectCandidates: Failed empty-vector-combine-blsct

i think this may not be related to this PR since i've seen this before.

**Comment by navbuilder** [comment]
A new build of aaa8dae0a9ec8067fe568d8618353b8cb72ccb08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/broadcast_after_version

**Review by 0x2830 — APPROVED** [review]

**Comment by aguycalled** [comment]
> aggregation sessions are collecting candidates fine, but i see this message when trying to send mixed coins
> 
> 2021-04-14 18:25:30 ERROR: AggregationSession::SelectCandidates: Failed empty-vector-combine-blsct
> 
> i think this may not be related to this PR since i've seen this before.

i will look into possible causes of this error, but initially id say its not related to this pr

**Review by chasingkirkjufell — APPROVED** [review]

**Pull request merged**
