### PR TITLE
Fix for a wallet crash related to encryption detection

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by aguycalled** [comment]
changes read good, will approve once magpie confirms it solves the issue

**Review by aguycalled — APPROVED** [review]
magpie confirmed fix

**Review by chasingkirkjufell — APPROVED** [review]

**Comment by magpie17** [comment]
Hello all, I was the person who discovered this wallet crash and did some troubleshooting in my live wallet to assist mxaddict in narrowing down what needed to be fixed (see dev-navcoin-core channel in the discord server for proof). If there is a bounty available for discovering this issue, I would like to claim it. Thanks, @magpie17

**Comment by aguycalled** [comment]
hi @magpie17 yes you can get a bounty for this. please leave a navcoin address here or send me through discord private message and i will send it to you

**Comment by magpie17** [comment]
Thanks Alex, just sent you a DM in discord with my NAV address.

**Pull request merged**
