### PR TITLE
Add gettoken and mine option to list tokens

### PR DESCRIPTION
**Pull request by aguycalled**
This Pull Request adds a new rpc command `gettoken` and a `mine` parameter to `listtokens` to show only tokens with balance.

### CODE REVIEW

**Comment by mxaddict** [comment]
Away from my main PC right now, will wait for gitian build to test

**Comment by chasingkirkjufell** [comment]
is gitian not building? ima try to build it locally

**Comment by aguycalled** [comment]
https://build.nav.community/binaries/aguycalled%3Atokens-rpc/

**Comment by navbuilder** [comment]
A new build of ab87a95e9ae1278a81d91244bae37503eccb00fb has completed succesfully!
Binaries available at https://build.nav.community/binaries/tokens-rpc

**Comment by chasingkirkjufell** [comment]
image

**Comment by chasingkirkjufell** [comment]
gettoken seems to work as intended, but listtokens mine is returning an error

**Review by chasingkirkjufell — APPROVED** [review]

**Review by mxaddict — APPROVED** [review]

**Pull request merged**
