### PR TITLE
Sweepprivkey

### PR DESCRIPTION
**Pull request by sherlockcoin**
Importprivkey + SweepPrivKey Functions and GUI work in progress.

### CODE REVIEW

**Comment by sherlockcoin** [comment]
Add a "Sweep Private Key" feature #315

**Comment by aguycalled** [comment]
pull requests should be atomic, its needed you remove code references to the dmg background pr.

please also note the new rpc command should be covered by a test

**Comment by sherlockcoin** [comment]
My bad. Will re-commit.

**Comment by mxaddict** [comment]
utACK, @sherlockcoin, you might need to rebase on master or merge master to this branch

**Comment by aguycalled** [comment]
from what i read in the code, the implementation is also wrong. you are scanning through the wallet's transactions outputs with the address the user wants to sweep, while you would need to scan the whole chain.

**Comment by sherlockcoin** [comment]
I'm working on a different approach to this, will close and reopen. :)

**Comment by mxaddict** [comment]
@sherlockcoin were you able to get work on this?

**Pull request closed without merging**
