### PR TITLE
Fix reference to chain tip

### LINKED ISSUE #631: -reindex corrupts the blockindex
## How to reproduce

- Launch a fully synced wallet with `-reindex=1`

## Issue description

- Reindex will fail:

```
2019-11-17 20:27:25 Reindexing block file blk00010.dat...
2019-11-17 20:27:50 ERROR: AcceptBlock: cold-staking-not-enabled (code 16)
2019-11-17 20:27:51 Loaded 181320 blocks from external file in 25395ms
2019-11-17 20:27:51 Reindexing block file blk00011.dat...
2019-11-17 20:27:53 Reindexing block file blk00012.dat...
2019-11-17 20:27:55 Reindexing block file blk00013.dat...
2019-11-17 20:27:57 Reindexing finished
```

- It will not accept the valid block `e5e9e23e134e4bd4b4a88542b4fd771373a6c6420eb3a48a7145dd5c2e1b5692`, which includes the first cold staking transaction, marking it as invalid

- The wallet will start to sync from scratch again, and will stop syncing once it finds the block `e5e9e23e134e4bd4b4a88542b4fd771373a6c6420eb3a48a7145dd5c2e1b5692`.

## What to expect when it is fixed

- Wallet should show a correct sync and state after reindexing.

## System specs

**Self build with depends folder of master @ b8ed018** 

Tested a GUI wallet:

- Bootstrap no indexes :white_check_mark:
  - `verifychain 4 0` rpc command succeeds :x: Failed :x: Issue #630 

Specs:

- Intel Core i7 2,8 Ghz 4 core, 16GB RAM, 1TB SSD
- OSX Mojave 64 bits
- Apple clang version 11.0.0 (clang-1100.0.33.12)
- Apple LLVM version 11.0.0 (clang-1100.0.33.12)

### PR DESCRIPTION
**Pull request by aguycalled**
Fixes #631

See issue for more details.

#### What to test

- Launch a fully synced wallet with `-reindex=1`. Wallet should show a correct sync and state after reindexing.

### CODE REVIEW

**Comment by aguycalled** [comment]
Tested and verified on my side.

**Comment by navbuilder** [comment]
A new build of ab2c02c52a831ec02c9ae2963b531170b57cc20d has completed succesfully!
Binaries available at https://build.nav.community/binaries/early-coldstake-check

**Comment by aguycalled** [comment]
Confirmed fix in:

Ryzen 3900x 12 core, 64GB RAM CL16 DDR4-3600, 1TB NVMe SSD
Hackintosh with Catalina OSX.
Gitian build ab2c02c with no indexes

**Comment by chasingkirkjufell** [comment]
Confirmed fix in:
Intel(R) i7-5820K 6 core, 64 GB RAM DDR4-2666 mSATA 500GB SSD
Windows 10 Pro
Gitian build ab2c02c with no indexes

**Comment by proletesseract** [comment]
Built fine, trying to reindex now. 

What is the material difference in moving the cold staking check to `ContextualCheckBlock` rather than where it used to be in `CheckBlock` and using `pindexPrev` vs `chainActive.Tip()`

**Comment by mxaddict** [comment]
@aguycalled I noticed that running `-reindex=1` on the GUI wallet hangs the wallet.

Maybe we should have the re-index run on the splash screen?

**Comment by mxaddict** [comment]
@aguycalled Is this normal?
```
2019-11-22 09:34:42 Loaded 248168 blocks from external file in 66481ms
2019-11-22 09:34:42 Reindexing block file blk00001.dat...
2019-11-22 09:35:41 Loaded 229165 blocks from external file in 59169ms
2019-11-22 09:35:41 Reindexing block file blk00002.dat...
2019-11-22 09:36:38 Loaded 229585 blocks from external file in 56184ms
2019-11-22 09:36:38 Reindexing block file blk00003.dat...
2019-11-22 09:37:47 Loaded 259107 blocks from external file in 69396ms
2019-11-22 09:37:47 Reindexing block file blk00004.dat...
2019-11-22 09:38:58 Loaded 299980 blocks from external file in 71071ms
2019-11-22 09:38:58 Reindexing block file blk00005.dat...
2019-11-22 09:40:04 Loaded 263250 blocks from external file in 66136ms
2019-11-22 09:40:04 Reindexing block file blk00006.dat...
2019-11-22 09:40:58 Loaded 215839 blocks from external file in 54109ms
2019-11-22 09:40:58 Reindexing block file blk00007.dat...
2019-11-22 09:42:13 INFO: Updating prices
2019-11-22 09:42:16 INFO: Updated prices
2019-11-22 09:42:20 Loaded 257070 blocks from external file in 81459ms
2019-11-22 09:42:20 Reindexing block file blk00008.dat...
2019-11-22 09:43:40 Loaded 286300 blocks from external file in 80140ms
2019-11-22 09:43:40 Reindexing block file blk00009.dat...
2019-11-22 09:44:50 Loaded 292554 blocks from external file in 69720ms
2019-11-22 09:44:50 Reindexing block file blk00010.dat...
2019-11-22 09:45:46 Loaded 226447 blocks from external file in 56297ms
2019-11-22 09:45:46 Reindexing block file blk00011.dat...
2019-11-22 09:46:34 Loaded 197691 blocks from external file in 48141ms
2019-11-22 09:46:34 Reindexing block file blk00012.dat...
2019-11-22 09:47:21 Loaded 192939 blocks from external file in 47162ms
2019-11-22 09:47:21 Reindexing block file blk00013.dat...
2019-11-22 09:48:13 Loaded 214344 blocks from external file in 51964ms
2019-11-22 09:48:13 Reindexing block file blk00014.dat...
2019-11-22 09:49:09 Loaded 233454 blocks from external file in 55334ms
2019-11-22 09:49:09 Reindexing block file blk00015.dat...
2019-11-22 09:49:14 Loaded 25054 blocks from external file in 5661ms
2019-11-22 09:49:14 Reindexing finished
2019-11-22 09:49:14 Pre-allocating up to position 0x100000 in rev00000.dat
2019-11-22 09:49:14 UpdateTip: new best=f73048d6e35d6af1ffe545cc8afbd3fe235b31fadc72e8639c7da5c195835d75 height=1 version=0x00000007 log2_work=17.000022 tx=2 date='2016-05-12 16:51:44' progress=0.000000 cache=0.0MiB(1tx)
2019-11-22 09:49:14 UpdateTip: new best=54dafdf7e67f00fd09e64ace51e26fb7e3fb2ade3865225b94e9601a3a24cc36 height=2 version=0x00000007 log2_work=17.584985 tx=3 date='2016-05-12 16:55:18' progress=0.000000 cache=0.0MiB(2tx)
2019-11-22 09:49:14 UpdateTip: new best=948af872d5c9e62196b231cbdc9e19c1f4b1a43c4bef901ada50d55e3417c22e height=3 version=0x00000007 log2_work=18.000022 tx=4 date='2016-05-12 16:55:25' progress=0.000000 cache=0.0MiB(3tx)
2019-11-22 09:49:14 UpdateTip: new best=0ae57a49a9d2bd55b18c399a8bb48a687b46e3472a7ae78f60bcdc68e6514cdc height=4 version=0x00000007 log2_work=18.33992 tx=5 date='2016-05-12 16:55:33' progress=0.000000 cache=0.0MiB(4tx)
2019-11-22 09:49:14 UpdateTip: new best=6947b438b13fb729ca69e72454816fe40019644c6d80cbd541df6425fbd114b7 height=5 version=0x00000007 log2_work=18.629698 tx=6 date='2016-05-12 16:55:39' progress=0.000000 cache=0.0MiB(5tx)
```

**Comment by mxaddict** [comment]
It seems like after the re-index, it started syncing from genesis block (I think it's not syncing from network though)

**Comment by aguycalled** [comment]
Yes. https://bitcoin.stackexchange.com/questions/60709/when-should-i-use-reindex-chainstate-and-when-reindex

Reindexing....Loaded... is related to the blockindex
UpdateTips related to the chainstate

**Comment by proletesseract** [comment]
I know this has already been merged, but I can confirm my node successfully reindexed overnight.

**Pull request merged**
