### PR TITLE
[RPC] Address history index

### PR DESCRIPTION
**Pull request by aguycalled**
This PR adds a new RPC method `getaddresshistory`. Related to #722 

getaddresshistory

Returns the history for an address(es) (requires addressindex to be enabled).

Arguments:
```
{
  "addresses"
    [
      "address"  (string) The base58check encoded address
      ,...
    ]
  "start" (number, optional) The start block height
  "end" (number, optional) The end block height
}
```

Result:
```
[
  {
    "block": (integer) the block height when this entry was seen
    "txindex": (integer) the index of the transaction inside of the block
    "time": (integer) timestamp when this entry happened
    "txid": (string) hash of the transaction
    "address": (string) the address affected
    "changes": {
      "balance": (signed integer) the change in spendable balance
      "stakable": (signed integer) the change in stakable balance
      "voting_weight": (signed integer) the change in voting weight
      "flags": (integer) 1 if is a coinstake or coinbase transaction, 0 otherwise
    },
    "result": {
      "balance": (integer) the spendable balance after the change
      "stakable": (integer) the stakable balance after the change
      "voting_weight": (integer) the voting weight after the change
    }
  }
]
```

Examples:
```
> navcoin-cli getaddresshistory '{"addresses": ["NNX4j3QtATFGMTFiAxdVDGR5mwL4v8Q57o"]}'
> navcoin-cli getaddresshistory '{"addresses": ["Y65KbGXT3SHSMjHBAYsB3fgpsqJ9Jp1PwstgNYG8X1AgbmevmkA5mCkG6E79K"]}'
> navcoin-cli getaddresshistory '{"addresses": ["4Eea43rawnG5uF4DVS3ZwPhAcNpxhHCD8R2AjyZi5MZjCFW7fCSY59FfsEe5YfKTvBjRudiAjEtmnMr9LHgbjosRN"]}'
```
When cold staking or cold staking v2 addresses are queried, it will print results from the individual addresses part of the cold staking address in their role.

### CODE REVIEW

**Comment by mxaddict** [comment]
Looks good, will test in a few hours

**Comment by navbuilder** [comment]
A new build of 038e06061618c931dbb337cc9e6788311209f1e0 has completed succesfully!
Binaries available at https://build.nav.community/binaries/address-history

**Comment by navbuilder** [comment]
A new build of c16b6f54762f5107c037d34af988b64be883f3ac has completed succesfully!
Binaries available at https://build.nav.community/binaries/address-history

**Comment by navbuilder** [comment]
A new build of 65fe893e4c56dd5798b6e014371354c7b06e9b46 has completed succesfully!
Binaries available at https://build.nav.community/binaries/address-history

**Comment by aguycalled** [comment]
added count of balance of staking-active addresses to `getstakinginfo` to substitute the functionality from navexplorer

**Comment by navbuilder** [comment]
A new build of 79b872239502532f1b395bb1e88196568436a894 has completed succesfully!
Binaries available at https://build.nav.community/binaries/address-history

**Comment by mxaddict** [comment]
Tested gitian built: https://build.nav.community/binaries/address-history/navcoin-5.0.1-x86_64-linux-gnu.tar.gz

Works fine on ubuntu 18.04

**Comment by navbuilder** [comment]
A new build of 36f7c085ed999315fb3dd5874692e8c09fddf7b5 has completed succesfully!
Binaries available at https://build.nav.community/binaries/address-history

**Pull request merged**
