### PR TITLE
Added FAILFAST for functional test suite

### PR DESCRIPTION
**Pull request by mxaddict**
Added FAILFAST for functional test suite to decrease build time and not waste CI time on a failed build.

### CODE REVIEW

**Comment by aguycalled** [comment]
ACK

**Comment by mxaddict** [comment]
Failfast working on travis: https://travis-ci.org/navcoin/navcoin-core/jobs/541789717#L1795

**Comment by mxaddict** [comment]
Reopened (This should speed up our test suite until we get the new functional-test branch work done.

**Comment by aguycalled** [comment]
waiting for travis

**Pull request merged**
