### PR TITLE
Improved the response logging for curl call to price info

### PR DESCRIPTION
**Pull request by mxaddict**
image

### CODE REVIEW

**Comment by aguycalled** [comment]
do we want to merge this or do we just want to get binaries from gitian so pclark can test it?

**Comment by mxaddict** [comment]
I think we should merge it as it will help with further debugging in the future if anyone else get's issues with the price info.

Or we can just use the build to help debug for pclark.

I'll leave it up to you.

**Comment by aguycalled** [comment]
how often would it print to the debug? it it's too often, then we should only debug when some flags are enabled in the config file (debug=prices, for example) if we wanted to merge

**Review by chasingkirkjufell — APPROVED** [review]

**Comment by mxaddict** [comment]
@aguycalled I think we should merge this after the build, but I think it's ready for review

**Comment by navbuilder** [comment]
A new build of cc7a99cd56af89a4332347b1fb3c896001a92272 has completed succesfully!
Binaries available at https://build.nav.community/binaries/improved-logging-for-price-info-response

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
