### PR TITLE
[RPC] Fix for getaddresshistory balance of multiple addresses

### PR DESCRIPTION
**Pull request by aguycalled**
When getaddresshistory is queried for multiple addresses, it was showing incorrect accumulated balances. Instead it should show the correct balance of each address.

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 12bbfb0e4db94e65d8e24474c0f4d01752782b1a has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-11-1

**Comment by navbuilder** [comment]
A new build of 97ca92110eae4dd88d36cf50753555b1573f341a has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-11-1

**Comment by mxaddict** [comment]
Changes look good, will test once I get on my main PC

**Comment by mxaddict** [comment]
Tested the RPC on devnet with Ubuntu 18.04 self built binary

**Pull request merged**
