### PR TITLE
DAO protocol upgrade

### PR DESCRIPTION
**Pull request by aguycalled**
This PR proposes changes in the DAO voting system signalled by version bit 11.

### Super Proposals

Super Proposals do not take coins out of the Community Fund but print them new.

Super Proposals can be created through the GUI or using the `createproposal` RPC command by setting to `true` the `super` parameter.

They are signalled in the RPC commands with `super_proposal` set to `true`.

Requirement for approval is 75% quorum and 90% acceptance.

#### What to test

- Super Proposals only work when the deployment is active.
- Super Proposals are only approved with the specified requirements.
- Super Proposals do not depend on the amount available on the Community Fund.
- Approval, rejection, expiration, block reorganisation do not affect the amount available in the Community Fund.
- Both RPC and GUI functionality work correctly.

### Combined voting of consensus parameters

Not implemented in GUI yet, only in RPC commands.

A combined vote for change of consensus parameters can be started using the RPC command `proposecombinedconsensuschange`.

Example:

`proposecombinedconsensuschange '[1, 2]' '[100, 100]'`

Additional values can be proposed with `proposeanswer`:

`proposeanswer f54c67f64fa1be51f23d9739d1f6b6a8e10d73f81ea8b7438445b3e52371ba43 '[150, 100]'` 

#### What to test

- Combined votes only work when the deployment is active.
- Combined votes can't be created when at least one of the indicated consensus parameters already has a voting active.
- Voting for those consensus change proposals work correctly.
- Proposed answers can't be duplicated.
- Proposed answers can't be the current value of the consensus parameters.
- RPC functionality work correctly.
- Please add as a comment to the Pull Request which parts of the GUI would need to be adapted to allow interaction with this new kind of votes.

### CODE REVIEW

**Comment by mxaddict** [comment]
@aguycalled  seems this PR has a few conflicts with latest master

**Comment by aguycalled** [comment]
> i'd try to add this to the stressor and run it

would you like to add it yourself or should I add it?

**Comment by navbuilder** [comment]
A new build of a91aa2367d6ee07cdd33773a22a3e02a9dbe4ee8 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Comment by navbuilder** [comment]
A new build of 32308f84f706b0ea86f6c88b0894e64dc4247b71 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Comment by navbuilder** [comment]
A new build of e7c0d04500aa16716a4d65d173f451aa3d69943a has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Comment by navbuilder** [comment]
A new build of 913711353a08ed60ea3ad2f1d21a93ea908b3c68 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Comment by navbuilder** [comment]
A new build of f9bcb64780568936ed09e88bec75eacc30288313 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Comment by navbuilder** [comment]
A new build of 5c6d837ff87ac69ae93260f3de1d5e4ccd554732 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Comment by navbuilder** [comment]
A new build of 50009f3da3861b23f4ba6a04e2165883c9e9d1c4 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Review by chasingkirkjufell — APPROVED** [review]
updated stressor and stressed this PR with a local build on ubuntu 20.04

**Comment by mxaddict** [comment]
@aguycalled I'm doing final testing on this PR, once done will approve and merge, I think the GUI for the combined voting should be a seperate PR.

**Review by mxaddict — APPROVED** [review]

**Comment by navbuilder** [comment]
A new build of 87a95c610a38630479fb040293d1634a4d081976 has completed succesfully!
Binaries available at https://build.nav.community/binaries/super-dao

**Pull request merged**
