### PR TITLE
Updated all references to old Repo Address for NavCoin github current url

### PR DESCRIPTION
**Pull request by mxaddict**
Updated the gitlian-linux.yml Repo Address for NavCoin

I think this only works because github does auto redirect of old repo URL?

### CODE REVIEW

**Comment by aguycalled** [comment]
yes, navcoindev is the old account but i guess craig linked them. approved for merge

**Comment by mxaddict** [comment]
I think that it should match the repo url exactly as RFC for urls is case
sensitive.

I guess if we want we could rename the repo to lowercase as it is better
looking as a URL.

**Comment by aguycalled** [comment]
yes, i would rather rename the url @craigmacgregor

**Comment by craigmacgregor** [comment]
repo URL has been renamed to `navcoin` all lower case. please update PR

**Comment by mxaddict** [comment]
> organisation URL has been renamed to `navcoin` all lower case. please update PR

I've updated the PR

**Comment by craigmacgregor** [comment]
approved, re-running travis then will merge when it passes.

**Comment by craigmacgregor** [comment]
`The job exceeded the maximum time limit for jobs, and has been terminated.`

:/

**Pull request merged**
