### PR TITLE
Updated the error log tab logic

### LINKED ISSUE #531: Error log tab bugs
The error log tab scrolls automatically to the bottom making impossible to read the content when new errors are constantly being added.

Additionally the ERROR log entries are only written to error.log and not to debug.log, making hard to identify the context of an error.

### PR DESCRIPTION
**Pull request by mxaddict**
closes #531

@aguycalled can you test and confirm this fixes the mentioned bugs?

### CODE REVIEW

**Comment by aguycalled** [comment]
tested debian

**Comment by proletesseract** [comment]
compiling and testing now.

**Comment by proletesseract** [comment]
compiles and runs on ubuntu 18.04

**Comment by aguycalled** [comment]
Paid d9de2e77b04020b79be19185943bf485da682b9bf598972bff0ee6db933fb13f

**Pull request merged**
