### PR TITLE
Revert net.cpp lock change

### PR DESCRIPTION
**Pull request by aguycalled**
Reverts a change in net.cpp locks for testing by bocyaj.

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 85130220e6be98545a01b75a729751806765c84e has completed succesfully!
Binaries available at https://build.nav.community/binaries/netcpp-lock

**Comment by navbuilder** [comment]
A new build of 2d2100acc7bbabaa82f0011e44dd4954c87150e5 has completed succesfully!
Binaries available at https://build.nav.community/binaries/netcpp-lock

**Comment by mxaddict** [comment]
@aguycalled  anything we need to test on this PR?

**Comment by aguycalled** [comment]
stability. bocyaj was testing it

**Review by mxaddict — COMMENTED** [review]
> stability. bocyaj was testing it

I see, I'll ping him on discord to see if he has any findings

**Pull request closed without merging**
