### PR TITLE
Update wallet with new logos

### PR DESCRIPTION
**Pull request by aguycalled**
Updates the wallet with the new logos from https://github.com/anquii/navcoin-assets

image

image

### CODE REVIEW

**Comment by chasingkirkjufell** [comment]
I think anquii has an updated one with a light grey ring. Or is this the latest version?

**Comment by aguycalled** [comment]
i think the grey gets confused with the grey background

**Comment by aguycalled** [comment]
updated background to white

image

**Review by chasingkirkjufell — APPROVED** [review]

**Comment by navbuilder** [comment]
A new build of 0b05e06f65850fb4c2a0c8024d4cbac2d0de618b has completed succesfully!
Binaries available at https://build.nav.community/binaries/new-logos

**Review by mxaddict — APPROVED** [review]

**Pull request merged**
