### PR TITLE
Added new progress ui for sync

### LINKED ISSUE #385: GUI improve for core wallet - blockchain syncing (Video Demo)
suggestionblockchainsync

### PR DESCRIPTION
**Pull request by mxaddict**
closes #385

### CODE REVIEW

**Comment by mxaddict** [comment]
Screenshot from 2019-06-13 06-51-15

**Comment by mxaddict** [comment]
@aguycalled Looks like the header counter is not working properly (Seems to load correct header count on load, but while syncing it shows block count instead of header count), I will fix that in the next push.

**Comment by mxaddict** [comment]
Header counter now updated to use `pindexBestHeader`

**Comment by mxaddict** [comment]
output

**Comment by mxaddict** [comment]
Travis build passed, I've also tested a full sync, too about 12 hours but UI showed correct functionality :+1:

**Comment by aguycalled** [comment]
Tested in OSX, working perfectly

**Comment by mxaddict** [comment]
@aguycalled  I remember wanting this feature like 6 months ago (Having seen it in DGB wallet)

I never thought I would be coding it into NAV myself! :rofl:

**Comment by proletesseract** [comment]
Builds and runs on ubuntu 18.04. Works as expected.

**Comment by aguycalled** [comment]
Paid 8e023b42fb899433938309b69b3fa71829cdd465ef9a8880eeeee8a1a85909f1

**Pull request merged**
