### PR TITLE
dotNAV

### PR DESCRIPTION
**Pull request by aguycalled**
This Pull Request introduces the consensus changed needed for a naming system dubbed dotNAV secured by Navcoin's blockchain and signalled for activation with version bit 34 (using block header's nonce).

Names are only allowed with the suffix `.nav` and to have a maximum length of 64 characters. Only allowed characters are alphanumeric and `-`, and the first character can't be a `-`.

Valid names: `satoshi.nav` `satoshi-nakamoto.nav` `satoshi21.nav` `21satoshi.nav`
Invalid names: `-satoshi.nav` `satoshi_nakamoto.nav`

*RPC Command*: `registername name`

Examples:

`registername alex.nav`

Registration has a cost set by a consensus parameter (initially `10 NAV`) and lasts 400 days worth of blocks (modifiable through consensus parameters). Names can be renewed by everyone (not only the owner) with the rpc command `renewname name`. The name's expiry date will be set to 400 days worth of blocks after the moment of the renewal, and it will have the same cost as a registration.

After registration, it requires a minimum of 6 blocks to allow the set of values.

Each name can have different keys, each pointing to an arbitrary value. Those can be exclusively set by the owner of the name and each name has a maximum allowance of 1024 bytes of data.

Domains allow additionally one subdomain, which must stay in the same character set constrains as a name.

*RPC Command*: `updatename name key value`

Examples: 

`updatename alex.nav ip 127.0.0.1`
`updatename alex.nav email alex@nav.community`
`updatename personal.alex.nav email alex.home@nav.community`

Names can be resolved through the RPC command `resolvename name`

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 3ac0aa8120ac5614dcaaad9669fff968d93138e9 has completed succesfully!
Binaries available at https://build.nav.community/binaries/dotnav

**Comment by mxaddict** [comment]
@aguycalled do we have plans for a DNS server that would integrate with nav blockchain? It would be nice/cool to have full network support by having a dotNAV dns server!

**Comment by navbuilder** [comment]
A new build of a62b65b5029791ad8f06da9a65827ed9d8600485 has completed succesfully!
Binaries available at https://build.nav.community/binaries/dotnav

**Comment by navbuilder** [comment]
A new build of a4aa4efe0b85dfa32155adcf8aaf4989bc916470 has completed succesfully!
Binaries available at https://build.nav.community/binaries/dotnav

**Comment by chasingkirkjufell** [comment]
might want to update the description of 10 NAV to 10 xNAV

**Comment by navbuilder** [comment]
A new build of 05d1f55299bd19e94735f4c30bd4c82aa76e34de has completed succesfully!
Binaries available at https://build.nav.community/binaries/dotnav

**Comment by navbuilder** [comment]
A new build of 68c3d6bc88791a27b7376e1d9f806bf810ab5626 has completed succesfully!
Binaries available at https://build.nav.community/binaries/dotnav

**Comment by navbuilder** [comment]
A new build of 860e8198e0dce99a21da4b796a39c9e6d960634c has completed succesfully!
Binaries available at https://build.nav.community/binaries/dotnav

**Review by chasingkirkjufell — APPROVED** [review]
created a stressor and it passed

**Comment by mxaddict** [comment]
Did some more manual testing, and still running the stressor, but I think it looks good to merge.

If I find anything, will post a new issue.

**Review by mxaddict — APPROVED** [review]

**Pull request merged**
