### PR TITLE
Bump version and release notes v4.7.3

### PR DESCRIPTION
**Pull request by aguycalled**

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 78abd0fff31567761e77441c029e3b7d16e971e1 has completed succesfully!
Binaries available at https://build.nav.community/binaries/v473

**Comment by chasingkirkjufell** [comment]
I remember doxy file requires a version bump as well.

**Comment by aguycalled** [comment]
Addressed in 17e5a77

**Comment by navbuilder** [comment]
A new build of 17e5a771d63860ec691d6ce73be95416f4b5e9b3 has completed succesfully!
Binaries available at https://build.nav.community/binaries/v473

**Comment by mxaddict** [comment]
I'm starting up a node with latest master build.

**Pull request merged**
