### PR TITLE
Updated univalue based on upstream changes

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 91741c84eb3dccf6c948999a7b0fed49f7403e6d has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-univalue-2

**Comment by chasingkirkjufell** [comment]
Anything specific to test?

**Comment by mxaddict** [comment]
Just test the RPC commands work via CLI

Univalue is the lib that is used to parse and create JSON for the RPC commands

**Review by aguycalled — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]
tested local build on linux

**Pull request merged**
