### PR TITLE
new SVG icons

### LINKED ISSUE #552: Icon's inconsistent on navcoin-core
Icons on left are BTC icons on right are OURs:
Screenshot from 2019-07-02 17-26-44

It seems that our icons are inconsistent in theme/design

I like how BTC's icons are consistent, do you guys think it's worth the work to make these consistent for our project?

### PR DESCRIPTION
**Pull request by onlyoneAdam**
This pull request include the new SVG icons requested.

closes #552

My address for the payment is:

NZv8DGmFyf7niVtyWfnEgS3NWBTyT5XhX9

### CODE REVIEW

**Comment by mxaddict** [comment]
Nice, will review now!

**Comment by mxaddict** [comment]
@onlyoneAdam also the `about.svg` i think is using wrong font for the `NAV` text, it should look this this font: https://github.com/navcoin/navcoin-core/blob/master/src/qt/res/icons/splash.png

**Comment by mxaddict** [comment]
Nice work man! This will give the icons a nice fresh coat of paint!

**Comment by mxaddict** [comment]
@onlyoneAdam one last thing, the about.svg text is now not centered, last change, then I will aprove the PR :+1:

**Comment by mxaddict** [comment]
Should we merge this into master? It does not affect functionality for now, so should be fine/safe to merge

**Comment by mxaddict** [comment]
NVM my last comment :+1:

**Comment by aguycalled** [comment]
Paid dd646eecd53fbe3b84509d6cbd70a7fea86531b27ad2d7d812f776020d957647

**Pull request merged**
