### PR TITLE
[OSX] Upstream changes for OSX specific code

### PR DESCRIPTION
**Pull request by mxaddict**
Updated some OSX specific code from upstream

Most of the changes are for removing support for older QT versions

### CODE REVIEW

**Comment by mxaddict** [comment]
Weird, Travis build passed, but it still shows pending on the PR page

**Comment by sherlockcoin** [comment]
No conflicts detected with #514 
But recommended to be merged before #514

~SoopY~

**Comment by mxaddict** [comment]
Rebased on master to fix merge conflicts

**Comment by navbuilder** [comment]
A new build of 967dd8f5276f06807ed705921dbf241f6c1bf847 has completed succesfully!
Binaries available at https://build.nav.community/binaries/patch-21

**Comment by mxaddict** [comment]
Updated this PR with changes from master

**Comment by navbuilder** [comment]
A new build of d634858b396ee3a6e8c37c4bb25b4d402185bc97 has completed succesfully!
Binaries available at https://build.nav.community/binaries/patch-21

**Comment by mxaddict** [comment]
@proletesseract @chasingkirkjufell can you guys take a look at this PR?

**Comment by chasingkirkjufell** [comment]
I don't have OSX to test with so I could just do some regression testing on other OS if that's okay.

**Comment by mxaddict** [comment]
Sadly me either.

**Comment by mxaddict** [comment]
I don't think these files that I updated are actually used on other OS
builds.

**Comment by aguycalled** [comment]
is this pr still needed?

**Comment by mxaddict** [comment]
> is this pr still needed?

I actually don't remember, I think this was just an update from upstream.

**Comment by mxaddict** [comment]
I rebased this branch off of master, seems to be fine

**Comment by navbuilder** [comment]
A new build of b6e818d8ac5ae50ee02e4b7bf19e291adf8c90e1 has completed succesfully!
Binaries available at https://build.nav.community/binaries/patch-21

**Comment by mxaddict** [comment]
I ended up having to merge this branch into the `blsct-addict` branch, so I'll just close this now.

**Pull request closed without merging**
