### PR TITLE
[FIX] Wallet false positive on txdata encryption

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 227fdadefb06495ff658daa82be9d06aca1dd487 has completed succesfully!
Binaries available at https://build.nav.community/binaries/fix-false-positive-pin-unlock

**Comment by chasingkirkjufell** [comment]
the wallet still asks for pin at start for me with the gitian builds

**Comment by mxaddict** [comment]
> the wallet still asks for pin at start for me with the gitian builds

@chasingkirkjufell I pushed another commit, this should fix the issue on windows.

**Comment by chasingkirkjufell** [comment]
> > the wallet still asks for pin at start for me with the gitian builds
> 
> @chasingkirkjufell I pushed another commit, this should fix the issue on windows.

great. will test the gitian build

**Comment by navbuilder** [comment]
A new build of 1d5c284f7752fb4d5d7b4b162ab275ada23bfc2c has completed succesfully!
Binaries available at https://build.nav.community/binaries/fix-false-positive-pin-unlock

**Comment by mxaddict** [comment]
> A new build of [1d5c284](https://github.com/navcoin/navcoin-core/commit/1d5c284f7752fb4d5d7b4b162ab275ada23bfc2c) has completed succesfully!
> Binaries available at https://build.nav.community/binaries/fix-false-positive-pin-unlock

I tested the gitian build with the `wallet.dat` file that @chasingkirkjufell gave me, and it's now working as expected.

**Review by chasingkirkjufell — APPROVED** [review]
confirm fix with previously false locked wallet.dat on windows

**Comment by mxaddict** [comment]
> confirm fix with previously false locked wallet.dat on windows

@chasingkirkjufell could you share the wallet.dat with @aguycalled so he can use it for testing as well?

**Comment by aguycalled** [comment]
tested osx / windows

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
