### PR TITLE
[GUI] Add voting address to the cold staking wizard

### PR DESCRIPTION
**Pull request by aguycalled**
image

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of f8eca60c38c926e6ca9b7470df699150a0b6ba56 has completed succesfully!
Binaries available at https://build.nav.community/binaries/voting-address-wizard

**Comment by mxaddict** [comment]
Changes look good, will test after I get some food 👍

**Comment by mxaddict** [comment]
Test windows 10 64 bit, worked as expected

**Comment by chasingkirkjufell** [comment]
image
suggesting putting Voting Address (optional):

**Comment by navbuilder** [comment]
A new build of 9d2444c6961b84f9f57c02dd13aff86d7b6f11de has completed succesfully!
Binaries available at https://build.nav.community/binaries/voting-address-wizard

**Pull request merged**
