### PR TITLE
Update httpserver.cpp header

### PR DESCRIPTION
**Pull request by garretlaxton**
httpserver.cpp:73:10: error: 'deque' in namespace 'std' does not name a template type
   73 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:32:1: note: 'std::deque' is defined in header '<deque>'; did you forget to '#include <deque>'?

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 7a2919b5ac14ba3b8a1dbf5aad08524db8d5ce08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/master

**Comment by navbuilder** [comment]
A new build of 7a2919b5ac14ba3b8a1dbf5aad08524db8d5ce08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/master

**Comment by navbuilder** [comment]
A new build of 7a2919b5ac14ba3b8a1dbf5aad08524db8d5ce08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/master

**Comment by navbuilder** [comment]
A new build of 7a2919b5ac14ba3b8a1dbf5aad08524db8d5ce08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/master

**Comment by navbuilder** [comment]
A new build of 7a2919b5ac14ba3b8a1dbf5aad08524db8d5ce08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/master

**Comment by navbuilder** [comment]
A new build of 7a2919b5ac14ba3b8a1dbf5aad08524db8d5ce08 has completed succesfully!
Binaries available at https://build.nav.community/binaries/master

**Comment by aguycalled** [comment]
@garretlaxton in what enviroment were you seeing that build issue?

**Comment by garretlaxton** [comment]
@aguycalled FreeBSD 12.1, I used the solution used on BTC for the same issue. https://github.com/bitcoin/bitcoin/pull/17249

**Comment by mxaddict** [comment]
Linux build still works after the change, I will assume that this fixes the FreeBSD issue and approve the PR

**Pull request merged**
