### PR TITLE
Add importmasterprivkey command

### PR DESCRIPTION
**Pull request by antonkolesnyk**
I need a way to import master private key, to make sure I can safely restore from paper wallet. Backing up to a USB stick is not a good option.
The work I did is pretty mechanical - it is possible that I am doing it entirely wrong. But I am happy to make changes per code review comments.

### CODE REVIEW

**Comment by aguycalled** [comment]
This implementation has nothing to do with importing a master private key to the wallet. It takes the supposedly private key as the wallet password, unlocks it and rescans for new transactions which is completely unnecessary after unlocking the wallet.

Adding an extra master private key to a wallet is not possible. Every wallet has a single one from which the new keys are derived. Multi-wallet support should be implemented in order to allow multiple wallets to be loaded at the same time, and therefor having different master private keys at the same time.

Another option would be to create an external tool which would create a new wallet.dat file from a given master private key to be later imported.

Anyway, if what you need is just to restore a paper wallet key (assuming you are using the one we provide on our website), it's enough using importprivkey - the private key on the paper wallet is not considered a master key and no new addresses are derived from there.

We are more than happy to receive contributions to the repository, but I'd kindly ask you to test the code you submit before opening a Pull Request.

**Comment by aguycalled** [comment]
I don't consider overwriting a wallet's private key is safe as it can compromise user's funds if wallet is not empty. I'd rather use external tools to generate a new wallet.
NavCoin wallets are HD, no need to backup the wallet regularly unless you import new keys not derived from the master private key.
Writing down an address private key on paper, moving coins to the address and removing the wallet file is considered safe, as long as there are no other different addresses than the one you backed up involved.

**Comment by deo1** [comment]
I posted this in the reddit thread.

When you send funds, it creates a new address to send the leftover staking coins to (the ones that weren’t sent).

You can work around this by sending “change” funds to a custom address in the GUI, but this could be error prone and inevitably someone out there only saved the original private key and doesn’t realize they have their funds spread across multiple addresses.

Importing masterprivkey does not work in the core wallet, as this was the first thing I tried.

I’d really love to have a single offline private key from which secondary keys are derived. Is there a way to store one key for the HD wallet from which all additional addresses that get created when transacting can be derived?

**Comment by aguycalled** [comment]
Please check: https://github.com/NAVCoin/navcoin-core/issues/113

**Pull request closed without merging**
