### PR TITLE
Updated the pollCheckBalance method to be more like upstream version

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of ccb3ddf71ee405076851340787e8b66992eaedcc has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-poll-changed-balance

**Comment by navbuilder** [comment]
A new build of 756950a61b897e6c6935c85cefc4f62c798bf203 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-poll-changed-balance

**Comment by navbuilder** [comment]
A new build of d932cc34eca1cf2054a5b369b81afc5e448a7d56 has completed succesfully!
Binaries available at https://build.nav.community/binaries/mxaddict:updated-poll-changed-balance

**Review by aguycalled — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]

**Comment by magpie17** [comment]
@mxaddict Hi just wondering if I was eligible for any testing bounty after alerting you to the "loading" issue that re-ocurred a few days ago and you fixed shortly after that? If so, please send to NQYPYEh8DspzHEX3nzTKhzrZiCWYYz9sas . Thanks.

**Comment by aguycalled** [comment]
I will send you a bounty

**Pull request merged**
