### PR TITLE
Update copyright years

### PR DESCRIPTION
**Pull request by aguycalled**

### CODE REVIEW

**Comment by mxaddict** [comment]
@aguycalled is there a reason some years are marked as 2020 and some are 2021 ?

**Comment by aguycalled** [comment]
it's the year when the files where modified

**Comment by mxaddict** [comment]
Got it, makes sense

**Review by mxaddict — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]

**Comment by navbuilder** [comment]
A new build of e026faa0c80625d268c563f60e1a8fdd99fd41c7 has completed succesfully!
Binaries available at https://build.nav.community/binaries/update-year

**Pull request merged**
