### PR TITLE
Revert patch to fix issues of transaction spending output from the memory pool

### LINKED ISSUE #814: Multi transaction in same block failed
This is crreated to log the issue reported by sakdeniz on discord.

When 2 transactions are sent within a short span, the 2nd one would fail.

2021-03-02 18:01:13 AcceptToMemoryPool: FAILED to add txn CTransaction(hash=65e6aaf45dc8796f3c166b79ceef424eb1d2d782e9d49cc77770aea832ba2470, nTime=1614708072, ver=3, vin.size=1, vout.size=2, nLockTime=22840), strDZeel=, vchTxSig= vchBalanceSig=)
    CTxIn(COutPoint(f5d67682f3, 0), scriptSig=483045022100f0b6a4a67c92, nSequence=4294967294)
    CTxOut(nValue=10.00000000, scriptPubKey=OP_DUP OP_HASH160 1f291d5f47f7a110d8a8bfdbcaf2400e872b43cf OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=979.99980000, scriptPubKey=OP_DUP OP_HASH160 835f9f89f941702a5cc02c0e931ef8264c79c9cf OP_EQUALVERIFY OP_CHECKSIG)
 to stempool ().
2021-03-02 18:01:13 CommitTransaction(): Error: Transaction not valid

### PR DESCRIPTION
**Pull request by aguycalled**
Fixes #814

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 351f9f7978e6326044f5e421b9cce525c5275cd2 has completed succesfully!
Binaries available at https://build.nav.community/binaries/fix_tx_same_block

**Comment by mxaddict** [comment]
@chasingkirkjufell how do I test this fix?

**Comment by chasingkirkjufell** [comment]
@mxaddict i think it's from sending two txes quickly in the same block using the same input? i'll play with it a but.

**Review by chasingkirkjufell — APPROVED** [review]
tested sending multiple public txes using the same input in the same block on windows 10 gitian build.

**Review by 0x2830 — APPROVED** [review]

**Pull request merged**
