### PR TITLE
Updated ./src/univalue from upstream

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by aguycalled** [comment]
what does this upgrade bring new?

**Comment by mxaddict** [comment]
> what does this upgrade bring new?

Mainly upstream changes from https://github.com/jgarzik/univalue

And upstream changes from https://github.com/bitcoin-core/univalue/pulls?q=is%3Apr+is%3Aclosed

The changes from jgarzik are more maintenance related (Some code cleanup + bug fixes)

The bitcoin-core changes seem to be for keeping the code working with the bitcoin-core wallet.

**Comment by proletesseract** [comment]
building on ubuntu 18.04 now

**Comment by mxaddict** [comment]
BTW, I think in the future we can have univalue and seck code be git subtrees and have lint step on travis check if it's updated from upstream repos

I'll make an issue so we don't forget.

**Pull request merged**
