### PR TITLE
[INDEX] Fix address balance

### PR DESCRIPTION
**Pull request by aguycalled**
Fixes https://github.com/navcoin/navcoin-core/issues/538. Without this PR the balance was not correctly accounted for addresses used as both cold staking and legacy spending addresses.

### CODE REVIEW

**Comment by mxaddict** [comment]
This was fast :P

**Comment by mxaddict** [comment]
I can't test it since I don't have a full node with indexes

Do we have a scenario I can test on testnet instead?

**Comment by mxaddict** [comment]
@sakdeniz can you give a test scenario?

**Comment by navbuilder** [comment]
A new build of af06dc7483a142fa6bf4435006fb8cbbea28c8a1 has completed succesfully!
Binaries available at https://build.nav.community/binaries/fix-addressbalanceindex

**Comment by mxaddict** [comment]
Tested on devnet with the scenario given via discord, working for me on Ubuntu 18.04

**Comment by chasingkirkjufell** [comment]
@sakdeniz reported the issue still exists and hopefully he can provide steps to replicate.

**Comment by mxaddict** [comment]
Yeah, I could not for the life of me replicate on devnet.

**Comment by mxaddict** [comment]
Was finally able to replicate the issue:
```
getaddressbalance '{"addresses":["mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y"]}'
{
  "balance": 20649890000,
  "received": 32949670000
}
```

```
"Confirmed","Date","Type","Label","Address","Amount (NAV)","ID"
"true","2020-06-05T18:27:39","Sent to","","mujGmsuuL7JurRNqmFBAifWYDNm2UmmZKH","-106.49890000","f8903e17378b671b6c4bfc673961f0c4ef51d4ca6dceb4fb28e6360597a1456b"
"true","2020-06-05T18:25:20","Staked","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","2.00000000","d8b7f07b01fd3eae9ed53d012b36d66383d0115f1c7b270644014a70b6f5f8fa"
"true","2020-06-05T18:23:44","Staked","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","2.00000000","ab4455c9105ca0e20e2a844d8637ac41295b1594f9ce8611a07a16a05bdfaa78"
"false","2020-06-05T18:22:40","Orphan","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","2.00000000","df2f761ecc74dce5c4168c7f2200d5f6a5ef16d55ea6c04a21b06a79701bc4b5"
"true","2020-06-05T18:19:01","Received with","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","100.00000000","89b0321ab6383c2a1eec606d692256c0bc87fd0248ddfd9e3c1f5e534c32d3e1"
"true","2020-06-05T18:18:37","Sent to","","mujGmsuuL7JurRNqmFBAifWYDNm2UmmZKH","-6.50110000","3af9eb7986c1559117fb70a1dc5a391c5814cc8ce7d5f3978fb02ab29c4b1e01"
"true","2020-06-05T18:17:20","Staked","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","2.00000000","8f6c69d9f9d6371f93592db14128b0ba5ae184ceb94046b3afb5512759e3175f"
"false","2020-06-05T18:16:48","Orphan","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","2.00000000","fc75e1f775d16cbb87c57e53d88e1f05c2fbba03f1721b610364af5719be4458"
"true","2020-06-05T18:15:41","Received with","","mxSedhHhcyQqry3ZLRTXeEvgz7J8TMwB8Y","7.00000000","77e614f6e93c449f5300f98d1b1a5a98ec9d41901f9fd42bcb999edb5e39e3cb"
```

**Comment by navbuilder** [comment]
A new build of f56da3c5bcbe83343dc920f50447ccc39f86dcde has completed succesfully!
Binaries available at https://build.nav.community/binaries/fix-addressbalanceindex

**Comment by mxaddict** [comment]
Should we merge?

**Pull request merged**
