### PR TITLE
[DAO] Do not transition to EXPIRED if previous state is ACCEPTED or REJECTED

### PR DESCRIPTION
**Pull request by aguycalled**
This PR prevents proposals or payment requests from transitioning to EXPIRED state if they were already ACCEPTED or REJECTED.

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of f5d4abe28404aabc0ccb2cf6cfadd77fe9ee1244 has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-12

**Comment by navbuilder** [comment]
A new build of f45de4c863213fd1aa9f1ec418420d2fe0588230 has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-12

**Comment by mxaddict** [comment]
Tested on testnet, seems to work fine, will load mainnet datadir and see how it goes.

@aguycalled I don't need to reindex anything when running this binary do I ?

**Comment by mxaddict** [comment]
@dantudor you might wanna check out this PR as well, this should fix issue with the finished/accepted proposals that are being marked as expired on navexplorer.

**Comment by mxaddict** [comment]
@aguycalled  shouldn't this be marked as accepted-expired instead of just expired?

image

**Review by mxaddict — APPROVED** [review]

**Comment by mxaddict** [comment]
@dantudor  @chasingkirkjufell can you guys take a look at this PR?

**Comment by chasingkirkjufell** [comment]
still seeing expired only and not accepted expired on my local build
image

**Comment by aguycalled** [comment]
> @aguycalled shouldn't this be marked as accepted-expired instead of just expired?
> 
> image

would need a reindex/resync

**Comment by aguycalled** [comment]
> still seeing expired only and not accepted expired on my local build
> image

should be fixed with last commit

**Review by chasingkirkjufell — APPROVED** [review]
tested local build on Ubuntu 20.04

**Comment by navbuilder** [comment]
A new build of db61dfe828c0527db01ec0647f40b9137aafb516 has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-12

**Comment by navbuilder** [comment]
A new build of 68dcb796bb3200341f4dd341ca0673e3ed73d829 has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-12

**Comment by navbuilder** [comment]
A new build of 6e01b19731b012fb34997b66cfb2ce186772d108 has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-12

**Comment by navbuilder** [comment]
A new build of aa9c7cbb64c8c9d89ba4f2d747d1d96b75d3375a has completed succesfully!
Binaries available at https://build.nav.community/binaries/aguycalled-patch-12

**Pull request merged**
