### PR TITLE
Use inventory for aggregation sessions and encrypted candidates

### PR DESCRIPTION
**Pull request by aguycalled**
This PR introduces a change in the way aggregation sessions and encrypted candidates are propagated.

Old model:
 - Nodes broadcast through dandelion (first using stem and later in fluff phase) the aggregation sessions and encrypted candidates in full to every node. Due to the size of encrypted candidates (2,6kb), this behaviour exhausts some nodes with low specs and reduces the performance of the wallet.

New model:
- Nodes broadcast an INVENTORY message using Dandelion with the hashes (32 bytes) of the aggregation sessions and encrypted candidates they now. The node will request the item's data, only if it's unknown for them, hence reducing the computational overhead and traffic.

What to test:

- Candidates progagate correctly in Devnet.

Notes:

Nodes running this version will not propagate to older versions, and won't receive from those. This change requires a majority of peers in the network to upgrade for a correct propagation of sessions and candidates.

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 0a3edfdb32760667642b03482ca54f983aceb842 has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of 07e62332362efa32bfbb86c69ee22dfeb72f3383 has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of 30a70a56fd1b30182e6bf4d5a28aa3e1233f24f5 has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of 773701e06f728167e0538f83c94670b726a4dbd4 has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of e07a06f228aec2a5acd1b39bc357286023de6bb5 has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of dd64e3c4d0fe3f8c704883ae0dfa5a1e5fe64a15 has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of 0914b8081d86a681c8c9c655f4d24ee30052e2ce has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of a94d4896e55ac836b36bd731af482a8633fabbaf has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Comment by navbuilder** [comment]
A new build of 65c3b69c623202ce999d9812cbac1b7a27bf09ee has completed succesfully!
Binaries available at https://build.nav.community/binaries/inv_xnav

**Review by mxaddict — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]
tested devnet private transaction broadcasting, mainnet staking

**Pull request merged**
