### PR TITLE
Updated the custom 'change' address to be a persistent setting

### LINKED ISSUE #518: QT Wallet does not save change address
When a change address is specified in coin control and the wallet is restarted this is lost.

### PR DESCRIPTION
**Pull request by mxaddict**
closes #518

* Address is saved in QSettings if valid
* Address is cleared from QSettings if invalid
* Address is unchanged if checkbox is ticked off/on
* Checkbox is saved in settings on change off/on

### CODE REVIEW

**Comment by sherlockcoin** [comment]
utACK looks good mate. :)

**Comment by mxaddict** [comment]
Rebased on master

**Comment by mxaddict** [comment]
Merged changes from master

**Comment by chasingkirkjufell** [comment]
tested 2 change addresses and toggling on and off then reboot on ubuntu 18.10. worked as expected.

**Comment by mxaddict** [comment]
@chasingkirkjufell updated the branch based on master

**Comment by chasingkirkjufell** [comment]
@mxaddict thanks. on ubuntu 18.10, after restarting the client, the text field showed up correctly with the custom change address but it does not actually do anything when a transaction is created. A new change address will be used despite the custom set one is correctly displayed in the test field.

**Comment by mxaddict** [comment]
Alright, I'll check it out.

**Comment by mxaddict** [comment]
@chasingkirkjufell I've fixed the bug you found in this PR

**Pull request merged**
