### PR TITLE
Add asm support in configure.ac and updated crc32c based on upstream changes

### PR DESCRIPTION
**Pull request by mxaddict**
NOTE: Left asm disabled by default since we need more changes to get it working properly

### CODE REVIEW

**Comment by mxaddict** [comment]
Merged master with this branch and seems build for osx is working with that

**Comment by mxaddict** [comment]
Fixed the issue with `make dist`

**Comment by navbuilder** [comment]
A new build of ee5754ae5fb22495d9553fe8262db4f7e16f3d24 has completed succesfully!
Binaries available at https://build.nav.community/binaries/add-asm-support

**Comment by aguycalled** [comment]
is this pr ready to merge?

**Comment by mxaddict** [comment]
I think so, tested devnet and wallet seemed to work as expected

**Review by chasingkirkjufell — APPROVED** [review]
tested local build on ubuntu 20.04

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
