### PR TITLE
Update the wallet GUI look and feel, fixed scaling on menu and splash screen (New Icons), Removed NavTech references, Added multi theme support

### LINKED ISSUE #252: GUI not rendering correctly when displayed in high res on Windows 10
Reports of users experiencing GUI warping at high resolutions. (3 cases, 2 confirmed at the same resolution)
OS: Windows 10
Screen Res: 3840x2160

Conjecture: Font size is increasing but the area for the font to render in isn't changing size to accommodate

image

### LINKED ISSUE #424: Remove focus highlighting when GUI elements selected
#### Improvement to wallet skin could be made when selecting widgets

x2dmasf

Small visual improvement that could be done throughout the wallet is removing the borders from selected and in focus widgets (especially buttons) to give the wallet a cleaner look. Can be done either via the navcoin style sheet 
```
    QPushButton:focus {
    	border: none;
    	outline: none;
 }
```

or manually/per widget if preferred
```
QWidget.setFocusPolicy(QtCore.Qt.NoFocus)
```

### LINKED ISSUE #465: Remove NavTech references
As NAVTech is not operative anymore, all the references in GUI, RPC commands, code, etc should be removed.

### LINKED ISSUE #548: Add a counter to the Community Fund button with count of pending votes
The Community Fund button on the top bar menu should show a red badge with the number of elements (proposals, payment requests, etc) which are still waiting to be voted.

### LINKED ISSUE #563: Integrate the new ICONs in `src/qt/res/icons/vector` into the wallet
Integrate the new ICONs in `src/qt/res/icons/vector` into the wallet.

### PR DESCRIPTION
**Pull request by mxaddict**
closes #548 
closes #563 
closes #465
closes #252 
closes #424

- [x] Removed Deprecated NavTech Code
- [x] Move menu to the side (From top)
- [x] Add new Dao Count Badge
- [x] Remove Dao pop up notification
- [x] Update menu icons to SVG from PNG
- [x] Update qt depends to compile SVG support
- [x] Update Dao count on change of proposal vote settings
- [x] Update Dao count on change of payment request vote settings
- [x] Update qt depends to compile SVG support (OSX Support)
- [x] Integrate new icons (SVG)
- [x] Add new Dao warning
- [x] Update Readme logo
- [x] Update `./share/pixmaps` logos
- [x] Update doxygen logo
- [x] Add new animation to splash screen
- [x] Fix scaling on QR Code on Receive / Request / Generate Cold Staking (HDPI screens)
- [x] Better looking tooltips
- [x] Add Multi Wallet Theme Support
- [x] Move status bar icons over to top right of the wallet
- [x] Update the overview page to look better and scale with HDPI screens
- [x] Make the TX list look better (Home page)
- [x] Add a GUI scaling option
- [x] Add Coin Control Toggle to send dialog/page
- [x] Integrate the theme into the new setup wizard
- [x] Make better use of the tx list space
- [ ] ~Create new bottom notifcations area~
- [ ] ~Move dao warning to notifications area~
- [ ] ~Move wallet sync warning to notifications area~
- [ ] ~Move NTP off warning to notifications area~

### CODE REVIEW

**Comment by mxaddict** [comment]
Screenshot from 2019-07-07 18-58-18

**Comment by mxaddict** [comment]
out

**Comment by mxaddict** [comment]
This is what it looks like with the new icons from @onlyoneAdam !

Screenshot from 2019-07-11 14-31-06

**Comment by mxaddict** [comment]
This is how the wallet looks now with the header.

Also fixed the disabled menu buttons text and icon color to stay same as default/normal colors

Screenshot from 2019-07-14 05-36-12

**Comment by mxaddict** [comment]
This is what the wallet looks like in different states

Screenshot from 2019-07-14 10-06-55
Screenshot from 2019-07-14 10-07-32
Screenshot from 2019-07-14 10-10-34
Screenshot from 2019-07-14 10-11-41

**Comment by aguycalled** [comment]
Testing in OSX.

Splash screen looks empty, wallet does not load.

image

```
$ ./src/qt/navcoin-qt -devnet -datadir=/Users/alex/navcoin-core/data2
objc[70040]: Class RunLoopModeTracker is implemented in both /usr/local/opt/qt@5.7/lib/QtCore.framework/Versions/5/QtCore (0x10ec82df0) and /Users/alex/navcoin-core/./src/qt/navcoin-qt (0x10d19ee10). One of the two will be used. Which one is undefined.
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QPixmap::scaled: Pixmap is a null pixmap
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinApplication(0x7ffee40ac8c8), parent's thread is QThread(0x7fc038d252b0), current thread is QThread(0x7fc038cd4320)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QSocketNotifier: Can only be used with threads started with QThread
QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinApplication(0x7ffee40ac8c8), parent's thread is QThread(0x7fc038d252b0), current thread is QThread(0x7fc038cd4320)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Could not parse stylesheet of object 0x7fc03b5c6ef0
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
```

**Comment by aguycalled** [comment]
```
$ ./src/qt/navcoin-qt -devnet -datadir=/Users/alex/navcoin-core/data2 -printtoconsole
objc[70401]: Class RunLoopModeTracker is implemented in both /usr/local/opt/qt@5.7/lib/QtCore.framework/Versions/5/QtCore (0x109600df0) and /Users/alex/navcoin-core/./src/qt/navcoin-qt (0x107b13e10). One of the two will be used. Which one is undefined.
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QPixmap::scaled: Pixmap is a null pixmap
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::removeTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QApplication::installTranslator: Please instantiate the QApplication object first
QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinApplication(0x7ffee97378a8), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QSocketNotifier: Can only be used with threads started with QThread
QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinApplication(0x7ffee97378a8), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
2019-07-15 09:25:02 



















2019-07-15 09:25:02 NavCoin version v4.6.0.0-73109763
2019-07-15 09:25:02 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
Could not parse stylesheet of object 0x7f89c377c560
2019-07-15 09:25:03 GUI: QObject: Cannot create children for a parent that is in a different thread.
(Parent is TrafficGraphWidget(0x7f89c8795140), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
2019-07-15 09:25:03 GUI: QMetaObject::connectSlotsByName: No matching signal for on_lineEdit_returnPressed()
2019-07-15 09:25:03 GUI: QMetaObject::connectSlotsByName: No matching signal for on_tabWidget_currentChanged(int)
2019-07-15 09:25:03 GUI: QMetaObject::connectSlotsByName: No matching signal for on_openDebugLogfileButton_clicked()
2019-07-15 09:25:03 GUI: QMetaObject::connectSlotsByName: No matching signal for on_errorLogCopyClipboardButton_clicked()
2019-07-15 09:25:03 GUI: QMetaObject::connectSlotsByName: No matching signal for on_sldGraphRange_valueChanged(int)
2019-07-15 09:25:03 GUI: QObject::startTimer: Timers can only be used with threads started with QThread
2019-07-15 09:25:03 GUI: QEventLoop: Cannot be used without QApplication
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
2019-07-15 09:25:03 GUI: QMetaObject::connectSlotsByName: No matching signal for on_okButton_accepted()
2019-07-15 09:25:03 GUI: QObject::connect: Cannot connect QAction::triggered() to (null)::quit()
2019-07-15 09:25:03 GUI: QObject::connect: Cannot connect QAction::triggered() to (null)::aboutQt()
2019-07-15 09:25:03 GUI: QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinGUI(0x7f89c37759a0), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
2019-07-15 09:25:03 INFO: Updating prices
2019-07-15 09:25:03 GUI: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QLabel(0x7f89c3692240), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
2019-07-15 09:25:03 GUI: QObject::startTimer: Timers can only be used with threads started with QThread
2019-07-15 09:25:03 INFO: Automatic price update set to 300000ms
2019-07-15 09:25:03 GUI: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QLabel(0x7f89c367a050), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
2019-07-15 09:25:03 GUI: QObject::startTimer: Timers can only be used with threads started with QThread
2019-07-15 09:25:03 GUI: QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinGUI(0x7f89c37759a0), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
2019-07-15 09:25:03 GUI: QObject::startTimer: Timers can only be used with threads started with QThread
2019-07-15 09:25:03 GUI: QObject: Cannot create children for a parent that is in a different thread.
(Parent is NavCoinApplication(0x7ffee97378a8), parent's thread is QThread(0x7f89c353d8f0), current thread is QThread(0x7f89c35e0cf0)
2019-07-15 09:25:03 GUI: QEventLoop: Cannot be used without QApplication
2019-07-15 09:25:04 INFO: Updated prices

```

**Comment by mxaddict** [comment]
Is that a native build? or using gitian?

**Comment by mxaddict** [comment]
BTW, did you rebuild depends dir before building the wallet?

**Comment by mxaddict** [comment]
Tested the windows build:

Capture

**Comment by mxaddict** [comment]
New Splash Screen animation
output

**Comment by mxaddict** [comment]
This is what the new menu looks like:

Screenshot from 2019-07-26 10-38-57

**Comment by mxaddict** [comment]
BUILDS here: 

http://static.codedmaster.com/nstake/navcoin-4.6.0-osx-unsigned.dmg
http://static.codedmaster.com/nstake/navcoin-4.6.0-win32-setup-unsigned.exe
http://static.codedmaster.com/nstake/navcoin-4.6.0-win64-setup-unsigned.exe

**Comment by proletesseract** [comment]
How is this one going @mxaddict ? ready for testing yet?

**Comment by mxaddict** [comment]
FIxed merge conflict with master branch

**Comment by proletesseract** [comment]
@mxaddict how are you going with this? There's some more conflicts to resolve. Is there anything we can do to help get this ready for review / merged?

**Comment by navbuilder** [comment]
A new build of ed0b6b0d9edaf1e452aad7c69c564c551d72860d has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 5ddcfb0b768fb3ef304da4f8abe7ab54ef4a3314 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 991d17b3e7b6f0c0ae30337955889fb5b55d63a0 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 67dea8308ae836fc3e31ff3edaee65a036b2d352 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 78a6618421d9237c0459eb2bf322aa307d60c072 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 96d195a090de3eb445d4b48f58670f621301fe6d has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of a6889b7871bdf3d6a87b88381beb40df7eeefe63 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 4a94842925a50e27ada99601daeff4622d3a4da0 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of b8e03807a3a2107aa1964f27b9103bff153b1761 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of b8e20fe6265f6b7d3ccd2f0a516e704ad05e4b16 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by chasingkirkjufell** [comment]
The currency conversion is not displayed in the new GUI:
New GUI
image

Should be:
image

**Comment by chasingkirkjufell** [comment]
text in DAO page is cut off
image

**Comment by chasingkirkjufell** [comment]
Text cut off in receive page
image

**Comment by mxaddict** [comment]
> text in DAO page is cut off
> image

This I think is a bug on the original UI for this page as well, and since @aguycalled changed this page alot, I think I should just leave it to avoid a conflict.

**Comment by mxaddict** [comment]
> Text cut off in history page
> image

I'll check this one out.

**Comment by mxaddict** [comment]
> The currency conversion is not displayed in the new GUI:
> New GUI
> image
> 
> Should be:
> image

I know the cause of this, fixing now.

**Comment by mxaddict** [comment]
@chasingkirkjufell 
Capture2
Capture

**Comment by navbuilder** [comment]
A new build of 3c8c5acee292965a1954c64537031d2b3a30c688 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by chasingkirkjufell** [comment]
Ubuntu 19.04 64 GB RAM

- [x] Review appearances of all pages
- [x] Create a proposal to see DAO notification
- [x] Vote on a proposal to see DAO notification going away
- [x] Cancel proposal vote to see DAO notification coming back up
- [x] Create a payment request to see DAO notification
- [x] Vote on a payment request to see DAO notification going away
- [x] Cancel payment request vote to see DAO notification coming back up
- [x] Create transactions to other nodes
- [x] Change display currency
- [x] Enabling/disabling coin control feature

Everything looks good so far. Still playing around with it. Will approve if all goes well for a few more days.

**Comment by navbuilder** [comment]
A new build of 157d2a03a80c6deaa8632bb82c1698aa65261c01 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by aguycalled** [comment]
By default the window size of my wallet is too big.
image
I need to manually resize it down to make it look good.
image
I would also suggest to add a vertical spacer between the Set up staking rewards button and the   Staking tab to fill the empty space in the tabs.
Everything else looking good to me so far ;)

**Comment by mxaddict** [comment]
The default size I think is cause by having the old wallet, old wallet is
taller, so the remembered size is taller when you open the wallet after
upgrading.

If you run the wallet on a machine that has not run the old wallet, size is
smaller if I recall correctly.

What do you mean by spacer on the setup staking button? Do you mean above
it?

**Comment by aguycalled** [comment]
image

It would look like this:

image

**Comment by aguycalled** [comment]
The first columns of the Balances and Staking tabs are misaligned:

image

**Comment by mxaddict** [comment]
Ok, good idea.

**Comment by mxaddict** [comment]
Balances and Staking reports now aligned.

Added the spacer above the setup staking button.

**Comment by mxaddict** [comment]
Capture

Looks like this now @aguycalled

**Comment by navbuilder** [comment]
A new build of 6eb883c2383466948aa71da0528271c36f24501b has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of bf6c6db6ad12f2aa6b82f2d3044cf6a834325ce8 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by mxaddict** [comment]
Added new coin control toggle to send page:
Capture

**Comment by mxaddict** [comment]
@aguycalled @chasingkirkjufell Added new NAV logo to the setup wizard main page:
Capture

**Comment by navbuilder** [comment]
A new build of d15c807781c1850f9e8cb710d039b231f21d7b95 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by mxaddict** [comment]
Applying the themes to the UI
Capture

**Comment by mxaddict** [comment]
Capture

**Comment by navbuilder** [comment]
A new build of f52b34f4c1433dc5f3f9a947df8b6cb849c91cd0 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by mxaddict** [comment]
Capture2

**Comment by mxaddict** [comment]
Capture

**Comment by mxaddict** [comment]
Capture4

**Comment by mxaddict** [comment]
Capture3

**Comment by navbuilder** [comment]
A new build of 9674499b835d789a6760551cdaa740de0789e935 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by dantudor** [comment]
Dragging and dropping seems rather laborious. Can it not be click on the next word to be placed in the list? Dragging 24 items into order won't be much fun

**Comment by mxaddict** [comment]
The changes I made in this PR are only for the theme, not the functionality
of the wizard.

Main functionality for the wizard is already on the master branch.

I like your idea, but will have to add it in a different PR.

**Comment by navbuilder** [comment]
A new build of 84dda353ba33a15182d31af690e06cd9a03bf4dd has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by dantudor** [comment]
I see, I've not been following closely, just saw the screenshots in my emails. UI loons like a great improvement!

**Comment by navbuilder** [comment]
A new build of 4bc6833abc35ce1706d922d5fb144580f4cb6abf has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by chasingkirkjufell** [comment]
logging anquii's suggestion on discord
"The splash screen is nice as well, but I’d reduce the logo a bit (perhaps like 10-15%). Talking about this one:"
image

**Comment by mxaddict** [comment]
I could keep the logo same size as the splash screen logo?

**Comment by chasingkirkjufell** [comment]
> I could keep the logo same size as the splash screen logo?
i believe that ought to work
image

**Comment by chasingkirkjufell** [comment]
Coin control page will open itself again after clicking ok
image

**Comment by navbuilder** [comment]
A new build of 284543100cc7feae905648921b59b47dd563bfc8 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of f51b2a05e2a38b75cbfa972ff79f56155e239a6b has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of ab56ee2fe0a1d604e247f013cb64d90c89e8cbc1 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 3c699936f734e6a7445e55fd37d2cf200751ce28 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by mxaddict** [comment]
Better use of the TX list space.
Capture2
Capture

**Comment by navbuilder** [comment]
A new build of 37a891bb4a024b22b1834147ae8e58c7d046cdb2 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 95e1c7debf66c0eb52941b5953e810840895ae09 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of 553c46b2392df989a67d1c80201d102e6226314d has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by navbuilder** [comment]
A new build of b49e7582fb171d8ea276eb20e97d45519c9cbaf8 has completed succesfully!
Binaries available at https://build.nav.community/binaries/updated-main-menu

**Comment by zanuka** [comment]
looking good, nice work 🚀

**Comment by mxaddict** [comment]
> looking good, nice work 🚀

Thanks!

**Pull request merged**
