### PR TITLE
[OSX] macdeployqtplus bug fixes [OSX]

### PR DESCRIPTION
**Pull request by sherlockcoin**
Background image of the OSX install window is mis-sized #379

### CODE REVIEW

**Comment by aguycalled** [comment]
@sherlockcoin would it be possible to automate the version which appears on the background? otherwise i think i would rather remove it and leave just `NAVCOIN CORE`

**Comment by sherlockcoin** [comment]
Sure! it is possible, just wanted to make sure people knew the right version when downloading the DMG.

**Comment by mxaddict** [comment]
utACK

**Comment by mxaddict** [comment]
I think these changes will require testing with gitian build

**Comment by sherlockcoin** [comment]
tACK 
QT GUI compiled and tested on OS X 10.12.6 (Sierra) - Non-deterministic.

**Comment by aguycalled** [comment]
gitian fails 

```
+ make osx_volname
echo NavCoin-Core >osx_volname
+ make deploydir
sed 's/PACKAGE_NAME/NavCoin Core/' < "contrib/macdeploy/background.svg" |  -f png -d 36 -p 36 | /usr/bin/convert - dpi36.background.tiff
/bin/bash: -f: command not found
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
convert: no images defined `dpi36.background.tiff' @ error/convert.c/ConvertImageCommand/3258.
make: *** [dpi36.background.tiff] Error 1
Makefile:1195: recipe for target 'dpi36.background.tiff' failed
```

**Comment by sherlockcoin** [comment]
Can you tell me the gitian system and dependencies please? Looks like an imagemagick error.

**Comment by sherlockcoin** [comment]
Found it! :) One moment.

**Comment by sherlockcoin** [comment]
@aguycalled is it possible to verify if its an imagemagick issue? Would it possible to reinstall imagemagick and re-test?

**Comment by aguycalled** [comment]
you can do it yourself, gitian is a deterministic build system we use, hence its importance the binaries can build there. it should be patched on this pr if its needed.

https://github.com/navcoin/navcoin-core/blob/master/doc/gitian-building.md

Von meinem iPhone gesendet

**Comment by sherlockcoin** [comment]
Indeed. I will do the needful. 👍

**Comment by sherlockcoin** [comment]
Screen Shot 2019-06-09 at 10 34 06 PM

Gitian Build success. :)

**Comment by sherlockcoin** [comment]
@mxaddict Thank you mate. It was quite a fix lol. 😄

**Comment by mxaddict** [comment]
@sherlockcoin the DMG looks nice and professional! Nice work! :+1:

**Comment by sherlockcoin** [comment]
> @sherlockcoin the DMG looks nice and professional! Nice work! 👍

Thank you mate. <3 Cheers! :)

**Comment by mxaddict** [comment]
BTW, I'm doing a gitian build for OSX now, and will ask @lordhace to check my build, will post results here :1st_place_medal:

**Comment by sherlockcoin** [comment]
Can @aguycalled  and everyone review and merge this? :)

**Comment by lordhace** [comment]
> BTW, I'm doing a gitian build for OSX now, and will ask @lordhace to check my build, will post results here 🥇

Works on OSX 10.13.6
navMacOS-1

**Comment by mxaddict** [comment]
Nice!

**Comment by sherlockcoin** [comment]
Awesome! :)

**Pull request merged**
