### PR TITLE
Removes embedded tor

### PR DESCRIPTION
**Pull request by aguycalled**
As xNAV mixing protocol uses now its own protocol, the embedded tor daemon is not necessary anymore.

### CODE REVIEW

**Comment by mxaddict** [comment]
Changes make sense, will wait for gitian build.

**Comment by navbuilder** [comment]
A new build of 9e53e2accd252930bd4ffe5821b9dffbb4e32928 has completed succesfully!
Binaries available at https://build.nav.community/binaries/remove-embedded-tor

**Review by mxaddict — APPROVED** [review]
Tested sending coins and basic wallet function via devnet, seems to be working.

**Comment by mxaddict** [comment]
@chasingkirkjufell have you had some time to test this PR?

**Comment by chasingkirkjufell** [comment]
> PR?

Not yet. But will have time tomorrow.

**Review by chasingkirkjufell — APPROVED** [review]
Gitian build on windows 10. Tested mainnet send, receive, and syncing.

**Pull request merged**
