### PR TITLE
Changes required for GLIBC backward compatibility with gitian builds

### LINKED ISSUE #482: PR #461 requires GLIBC 2.27 on x86_64 and i686 linux build
PR #461 requires GLIBC 2.27 on x86_64 and i686 linux build

We will need to add back compat code for symbols used to maintain compatibility for next navcoin release

We should use:
```
'80386':  GLIBC (2,1),
'X86-64': GLIBC (2,2,5),
```

### PR DESCRIPTION
**Pull request by mxaddict**
This closes #482 

~~These changes include some upstream changes to `./src/compat` code and gitian build for linux downgraded to `trusty` so that the linux binaries will use older GLIBC when linking~~

~~Windows and OSX builds remain on `bionic` as they did not have the GLIBC back compat issue~~

~~libcurl had to be downgraded back to 7.58.0 ( Which was the version before PR #461 )~~

EDIT:
All builds remain on `bionic`
Added more compat code to get `libunbound 1.9.0` and `libcurl 7.64` working with older GLIBC

### CODE REVIEW

**Comment by mxaddict** [comment]
I'm still building final gitian build locally, will post hashes once done.

**Comment by aguycalled** [comment]
can't test this till next week (monday)

**Comment by mxaddict** [comment]
Added `riscv64` support to the gitian builds

**Comment by mxaddict** [comment]
Gitian build hashes for 8d41032
```
USE_DOCKER=1 ./bin/gbuild -j10 --commit navcoin-core=patch-17 --url navcoin-core=https://github.com/mxaddict/navcoin-core.git ../navcoin-core/contrib/gitian-descriptors/gitian-linux.yml
USE_DOCKER=1 ./bin/gbuild -j10 --commit navcoin-core=patch-17 --url navcoin-core=https://github.com/mxaddict/navcoin-core.git ../navcoin-core/contrib/gitian-descriptors/gitian-win.yml
USE_DOCKER=1 ./bin/gbuild -j10 --commit navcoin-core=patch-17 --url navcoin-core=https://github.com/mxaddict/navcoin-core.git ../navcoin-core/contrib/gitian-descriptors/gitian-osx.yml
```

Hashes:
```
15882042293d9d6b4334fd5d5419258b6a70a22dd9afb6f20f73518727ea5e26  navcoin-4.6.0-i686-pc-linux-gnu-debug.tar.gz
1870d93cc34abefc3226e4046099acb5eca80764c76ecfd2899941b7d2150435  navcoin-4.6.0-osx64.tar.gz
271c451880a3b39643b754597efee88d19ad75c4c31987fadb1f4ac77d7b8a99  navcoin-4.6.0-arm-linux-gnueabihf.tar.gz
2b96b2a105ba75340a4b304b955a18bfbeafba82f71f7774da51ae14deabcf9f  navcoin-4.6.0-x86_64-linux-gnu-debug.tar.gz
3177b84f38f7a0907129c7237e885e6b5713b56bc8a9b9b9a8d2f16e78a9a650  navcoin-linux-4.0.0-res.yml
351658c247e4ec109457e6da6c7c657b1fbd22bdc3ea00822b32e44fbda488b3  navcoin-4.6.0-osx-unsigned.tar.gz
3f7aa169438c35570b77d1dbf82aadb2d40fbcf5633d3074cb7e7c940df76ef3  navcoin-4.6.0-win32-debug.zip
621afb4ad3adbef0023488d7ba700a678185f93607bc57c3c24536947c97b898  navcoin-4.6.0-win64.zip
6a6b48a33beb347da8151a8a54376eda818a8213d49ab1842c09b13dd7347f77  navcoin-4.6.0-arm-linux-gnueabihf-debug.tar.gz
6e347716710c78ce192b6c76133795e98ff259639b486a8c8c9e44c10f05d372  navcoin-win-4.0.0-res.yml
779f3d48ec37a13d594f9003b9c2054fe934c3e0fe9865f89c55a926464d79fd  navcoin-4.6.0-win64-setup-unsigned.exe
794601616371f9f009c0608a686d89c543acefaa33232979e63660ffdd74d002  navcoin-4.6.0-win32.zip
796a35610d88c138e64bb807c489909332eb92235e48f1f4b55763fe96fc33a0  navcoin-4.6.0-x86_64-linux-gnu.tar.gz
8188e96d3f62045b4826cbc185bab6776f9dc83fb8803539a44533f1378521ac  navcoin-4.6.0-win32-setup-unsigned.exe
925297dd4b1ecc2e873e17a09baa91dd029675cafb40c81d0477c1094617a863  navcoin-4.6.0-osx-unsigned.dmg
934aaa00ba32da4ee252081aa1fad523f27174cc030d867c3b874f5c3ec5b59d  navcoin-4.6.0-riscv64-linux-gnu-debug.tar.gz
9dd96b9dde23e0adfee5bbbd71b407acc6a0924efb93168c5b7685e55538a761  navcoin-4.6.0-i686-pc-linux-gnu.tar.gz
a099fe47bdf1c62da524cf53bf5be97754f83aa6183a358b1b76770c489e7217  navcoin-4.6.0-aarch64-linux-gnu-debug.tar.gz
b1dd88cdd8bf09af2539d0b345e647129d8fd55c92b6d824b6ecc53efd531028  navcoin-4.6.0-win.tar.gz
b69a33b051516b5146a2b5278d379789b173620d14d9bfc131bfaf0d6d0b1f46  src/navcoin-4.6.0.tar.gz
bdd4fe82002dc3e40b950072e467df333d6a5de35e5de6598f360032772e03b0  navcoin-4.6.0-riscv64-linux-gnu.tar.gz
e10ba8b0f4506237eb6b0094503a3253624a7771e6596fd73421d557e23abf05  navcoin-4.6.0-win64-debug.zip
ecf750a91880bc0a06d08e25f2436115b223737050b2213260b6239449e90b17  navcoin-osx-4.0.0-res.yml
edf6a9961b28647511d2fb8b7a3f6c6b0afac5da32dbd178556f5c428ab30ccd  navcoin-4.6.0-aarch64-linux-gnu.tar.gz
```

**Comment by proletesseract** [comment]
just a question, are you sure the flag should be `-j10` to specify the number processes? I thought it was `-j 10` with a space?

**Comment by mxaddict** [comment]
> just a question, are you sure the flag should be `-j10` to specify the number processes? I thought it was `-j 10` with a space?

Works either way :+1: I'm just used to not adding the space when doing `make -j#` calls, so I kinda do the same with gitian builds.

**Comment by mxaddict** [comment]
BTW @proletesseract I've tested the giian build on here, and I can confirm the pink color on the GUI on OSX.

I'll see if I can fix it and create a PR

**Comment by proletesseract** [comment]
ACK

**Comment by proletesseract** [comment]
im running the gitian build on this PR now to confirm hashes

**Comment by mxaddict** [comment]
@aguycalled I wanna change my bounty address to `XakMNvZREj5XWUTnLJWMqdU62vcoP3ksDY3HAoAEjtKhGLyUSakjLrMjgCuJN` for future bounties

**Comment by aguycalled** [comment]
hashes match for me too, tested osx/debian

**Comment by aguycalled** [comment]
Paid 1a630ac0f1736659e6362fd11eb8bee53d0e365b9f1a8640204f2a3690759bb2

**Pull request merged**
