### PR TITLE
Optimises multiexp operation

### PR DESCRIPTION
**Pull request by aguycalled**
This PR starts the migration to mcl as arithmetic library over the bls curve.

This will accelerate both the proof creation and verification times for blsCT.

To test: correct validation of the testnet chain

Benchmark with some test vectors:

```optimised took: 24.48ms
old method took: 108.49ms
optimised: 8db58befd4f1580c0e290cd33b789315b5eac8faad0f4f73d5cb1ed64f6ff427d53d613c233d5bdcec94d067478421e0
legaacy 8db58befd4f1580c0e290cd33b789315b5eac8faad0f4f73d5cb1ed64f6ff427d53d613c233d5bdcec94d067478421e0

optimised took: 17.10ms
old method took: 48.09ms
optimised: 80b87e985567ae4efa79c0d6a998aaaa7578fc52fe8ae3b4014c3f5535a679ed40fe30e86d16c3c734d5e44fc86047e1
legaacy 80b87e985567ae4efa79c0d6a998aaaa7578fc52fe8ae3b4014c3f5535a679ed40fe30e86d16c3c734d5e44fc86047e1

optimised took: 26.51ms
old method took: 96.74ms
optimised: 8ad823bfa7f82a8ab66f3216ebc420e5f1344df923682bfab7977a9ffc9a9a0099e0b0ce9215cd7dfc137b941bfbbf6f
legaacy 8ad823bfa7f82a8ab66f3216ebc420e5f1344df923682bfab7977a9ffc9a9a0099e0b0ce9215cd7dfc137b941bfbbf6f

optimised took: 17.20ms
old method took: 45.42ms
optimised: 9100fb7d0a910c37ec57d4076004930cfebc1f99ccaf3dc2a943588d9d5e117227c8d74a198bc5e095b1dc6d2757836b
legaacy 9100fb7d0a910c37ec57d4076004930cfebc1f99ccaf3dc2a943588d9d5e117227c8d74a198bc5e095b1dc6d2757836b

optimised took: 26.72ms
old method took: 94.74ms
optimised: a2c3dcc6afeef53e30bda3508061e3b871a64b29638a86b7fdb318d47daa1b0227ca99f2f2501e48bed9a2861af48683
legaacy a2c3dcc6afeef53e30bda3508061e3b871a64b29638a86b7fdb318d47daa1b0227ca99f2f2501e48bed9a2861af48683

optimised took: 73.38ms
old method took: 171.78ms
optimised: b2af8f02025e1010b73f56084bdd5d5257f921d939caf746cbfd76181364304bdf1e18e6f2af911369033e7af04a33f2
legaacy b2af8f02025e1010b73f56084bdd5d5257f921d939caf746cbfd76181364304bdf1e18e6f2af911369033e7af04a33f2

optimised took: 101.66ms
old method took: 359.80ms
optimised: 83c91e795d491897b34a576bcdd4723f2b0971f6845c67ca0ab6c5224b947b27e130dd5da2ecb5069c308ec52c8d1481
legaacy 83c91e795d491897b34a576bcdd4723f2b0971f6845c67ca0ab6c5224b947b27e130dd5da2ecb5069c308ec52c8d1481

optimised took: 19.77ms
old method took: 45.28ms
optimised: a0aa18e11c78748653161da73aac7bbe10a725faaabb17f9369efb73b6ddc817020a69e905e0c2040b8826700bb0a1ae
legaacy a0aa18e11c78748653161da73aac7bbe10a725faaabb17f9369efb73b6ddc817020a69e905e0c2040b8826700bb0a1ae

optimised took: 24.73ms
old method took: 90.07ms
optimised: 9114956f9f8f998b9e393cc4083bda64980b29959e25a58b6ae4195c6f73f2d6ae81473225a66cffa9802e31fad1cda5
legaacy 9114956f9f8f998b9e393cc4083bda64980b29959e25a58b6ae4195c6f73f2d6ae81473225a66cffa9802e31fad1cda5

optimised took: 19.59ms
old method took: 45.15ms
optimised: ab9a867818c6710552e0f3a5c20fcbb51cf8ab937f17999638ad8d76400ac52e43dbc4a3bf34af727554bffa8ebc6d73
legaacy ab9a867818c6710552e0f3a5c20fcbb51cf8ab937f17999638ad8d76400ac52e43dbc4a3bf34af727554bffa8ebc6d73

optimised took: 24.21ms
old method took: 91.06ms
optimised: 86cfc74665a7a53ef74804037b51ab36d90e86cd6fa1055c5943ccc0a62a8d91acbaa5d19bb5aa035fccebb9113a9c8b
legaacy 86cfc74665a7a53ef74804037b51ab36d90e86cd6fa1055c5943ccc0a62a8d91acbaa5d19bb5aa035fccebb9113a9c8b

optimised took: 18.57ms
old method took: 52.14ms
optimised: 80b87e985567ae4efa79c0d6a998aaaa7578fc52fe8ae3b4014c3f5535a679ed40fe30e86d16c3c734d5e44fc86047e1
legaacy 80b87e985567ae4efa79c0d6a998aaaa7578fc52fe8ae3b4014c3f5535a679ed40fe30e86d16c3c734d5e44fc86047e1

optimised took: 26.25ms
old method took: 90.46ms
optimised: 9458d42c0d4e7713297f0e38b8df6dcf4b8158b634c026cc8eacdc9ddeb3ea608284f712ed7267ae43e35f8cd0b8907d
legaacy 9458d42c0d4e7713297f0e38b8df6dcf4b8158b634c026cc8eacdc9ddeb3ea608284f712ed7267ae43e35f8cd0b8907d

optimised took: 18.95ms
old method took: 44.49ms
optimised: b0367f21b94a715aa30a00db474109b886d664fbaff01d19296afd06d08fb8bf1763661020ca2928b52da7b37e82a50f
legaacy b0367f21b94a715aa30a00db474109b886d664fbaff01d19296afd06d08fb8bf1763661020ca2928b52da7b37e82a50f

optimised took: 25.22ms
old method took: 95.96ms
optimised: 8fbdf66574b5beb2d0b3d8e1dd8f047001cacc9ab3092ce430ae11c0c74161780ef9dd7bb2465cbca7916249c6b3d031
legaacy 8fbdf66574b5beb2d0b3d8e1dd8f047001cacc9ab3092ce430ae11c0c74161780ef9dd7bb2465cbca7916249c6b3d031

optimised took: 74.25ms
old method took: 180.10ms
optimised: 886fa1f627498aba2249540c552a5f1ab0cf2e2d518cec1e492c7fb13921e6f40353884cfecf640a869ca2f21bbf5293
legaacy 886fa1f627498aba2249540c552a5f1ab0cf2e2d518cec1e492c7fb13921e6f40353884cfecf640a869ca2f21bbf5293

optimised took: 96.24ms
old method took: 362.25ms
optimised: aef0c2535de6fde5b4f4ea3d753b4aee77981c133fc0fca9913a3cbd9e8d710616776dec971d444d19a88fa11f928544
legaacy aef0c2535de6fde5b4f4ea3d753b4aee77981c133fc0fca9913a3cbd9e8d710616776dec971d444d19a88fa11f928544```

### CODE REVIEW

**Comment by chasingkirkjufell** [comment]
this is amazing. really well done :)

**Comment by mxaddict** [comment]
@aguycalled do you think we should release this in 6.0.1 or wait for next release?

**Comment by aguycalled** [comment]
yes, ideally with 6.0.1

**Review by 0x2830 — APPROVED** [review]
Approved! Good stuff

**Comment by mxaddict** [comment]
@aguycalled what is best way to test this out on devnet?

Do we have a python test for this?

**Comment by aguycalled** [comment]
the most important thing is that the new arithmetic library provides the same results as relic, so the best way to test is verifying that testnet syncs correctly. comparing sync speed with previous build in testnet would be interesting too.

for me it worked and way faster

**Comment by mxaddict** [comment]
> the most important thing is that the new arithmetic library provides the same results as relic, so the best way to test is verifying that testnet syncs correctly. comparing sync speed with previous build in testnet would be interesting too.
> 
> for me it worked and way faster

Ack, will test it out on testnet then.

**Comment by mxaddict** [comment]
@aguycalled is the gitian build for this stuck/broken?

**Comment by aguycalled** [comment]
it was waiting for my input 🤣 

image

going again now

**Comment by mxaddict** [comment]
> it was waiting for my input 🤣
> 
> image
> 
> going again now

I see, hopefully we can test and include this in 6.0.1 ? 👍

**Comment by chasingkirkjufell** [comment]
is gitian build stuck?

**Comment by aguycalled** [comment]
Gitian failing:

```
  CXX      libnavcoinconsensus_la-utiltime.lo                                                                                                                                          │···················
make[3]: Entering directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src/secp256k1'                                                                              │···················
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o                                                                                                │···················
make[3]: Entering directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src/mcl'                                                                                    │···················
echo                                                                                                                                                                                   │···················
                                                                                                                                                                                       │···················
make[3]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src/mcl'                                                                                     │···················
make[3]: Entering directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src/mcl'                                                                                    │···················
echo                                                                                                                                                                                   │···················
                                                                                                                                                                                       │···················
make[3]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src/mcl'                                                                                     │···················
  CXX      navcoind-navcoind.o                                                                                                                                                         │···················
In file included from navcoind.cpp:10:                                                                                                                                                 │···················
In file included from ./chainparams.h:11:                                                                                                                                              │···················
In file included from ./primitives/block.h:9:                                                                                                                                          │···················
In file included from ./primitives/transaction.h:10:                                                                                                                                   │···················
./blsct/bulletproofs.h:24:10: fatal error: 'mcl/bn_c384_256.h' file not found                                                                                                          │···················
#include <mcl/bn_c384_256.h>                                                                                                                                                           │···················
         ^~~~~~~~~~~~~~~~~~~                                                                                                                                                           │···················
gcc -g -O2 -Wall -Wextra -Wno-unused-function  gen_context.o -o gen_context                                                                                                            │···················
./gen_context                                                                                                                                                                          │···················
  CC       src/libsecp256k1_la-secp256k1.lo                                                                                                                                            │···················
1 error generated.                                                                                                                                                                     │···················
Makefile:10240: recipe for target 'navcoind-navcoind.o' failed                                                                                                                         │···················
make[2]: *** [navcoind-navcoind.o] Error 1                                                                                                                                             │···················
make[2]: *** Waiting for unfinished jobs....                                                                                                                                           │···················
  CCLD     libsecp256k1.la                                                                                                                                                             │···················
make[3]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src/secp256k1'                                                                               │···················
make[2]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src'                                                                                         │···················
Makefile:11056: recipe for target 'all-recursive' failed                                                                                                                               │···················
make[1]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-apple-darwin16/src'                                                                                         │···················
make[1]: *** [all-recursive] Error 1                                                                                                                                                   │···················
make: *** [all-recursive] Error 1                                                                                                                                                      │···················
Makefile:718: recipe for target 'all-recursive' failed                                                                                                                                 │···················
tail: 'gitian-builder/var/build.log' has become inaccessible: No such file or directory               
```

**Comment by mxaddict** [comment]
@aguycalled windows gitian build of this branch seems to work supprisingly...

**Comment by mxaddict** [comment]
Tested on testnet:
```
2021-02-16 22:34:53 UpdateTip: new best=77546c0df607001b53b35cf589087e039f63caf0901d4a0cff25257eae73b7c4 height=2681 version=0x7bc5e5f1 log2_work=203.17549 tx=4110 date='2020-11-26 01:09:04' progress=0.007033 cache=10.2MiB(3918tx)
2021-02-16 22:34:53 UpdateTip: new best=bb87c061bef3abbf31d337c5ef4fca237177f8383472353c8b40842be6bb8182 height=2682 version=0x7bc5e5f1 log2_work=203.17549 tx=4112 date='2020-11-26 01:09:20' progress=0.007037 cache=10.2MiB(3920tx)
2021-02-16 22:34:53 UpdateTip: new best=ca9f3bf9e3857f3b646991804734b6cd6f6a20ce025edbea9e9d80cb9dd8b34e height=2683 version=0x7bc5e5f1 log2_work=203.17549 tx=4114 date='2020-11-26 01:09:36' progress=0.007040 cache=10.2MiB(3922tx)
2021-02-16 22:34:53 UpdateTip: new best=1516da76a353acd2a13c53e1c38dbd0000279a00f064831e189d6672c50ac616 height=2684 version=0x7bc5e5f1 log2_work=203.17549 tx=4117 date='2020-11-26 01:10:08' progress=0.007045 cache=10.2MiB(3922tx)
2021-02-16 22:34:53 UpdateTip: new best=c21c2cf7b54c3e969da735c987ef412457474abe7a9fb9648a157cb80f5f9f3d height=2685 version=0x7bc5e5f1 log2_work=203.17549 tx=4119 date='2020-11-26 01:10:24' progress=0.007049 cache=10.2MiB(3924tx)
2021-02-16 22:34:53 UpdateTip: new best=5e5c9da7a61a9ca1f3fdd15f45583a2c8add646c8d3b3e3b853bf5c8301219f4 height=2686 version=0x7bc5e5f1 log2_work=203.17549 tx=4121 date='2020-11-26 01:12:00' progress=0.007052 cache=10.2MiB(3926tx)
2021-02-16 22:34:53 UpdateTip: new best=fb7ed1b003b9e8e76935f67342249505d2f6aaee9a467c96aba0b3a3cbf0c7c7 height=2687 version=0x7bc5e5f1 log2_work=203.17549 tx=4123 date='2020-11-26 01:12:16' progress=0.007056 cache=10.2MiB(3928tx)
2021-02-16 22:34:53 UpdateTip: new best=519530cc7ade16b02548210e908f7bed0fa4c9af3956ec20ba4c43334803fe93 height=2688 version=0x7bc5e5f1 log2_work=203.17549 tx=4125 date='2020-11-26 01:13:20' progress=0.007059 cache=10.2MiB(3930tx)
2021-02-16 22:34:54 UpdateTip: new best=64d3aa4d57166ddf3883b11a3e8c5b5053419638362e8f603f5c8570dfd749d2 height=2689 version=0x7bc5e5f1 log2_work=203.17549 tx=4127 date='2020-11-26 01:13:36' progress=0.007062 cache=10.2MiB(3932tx)
2021-02-16 22:34:54 UpdateTip: new best=db33bc5ae792029cb0bb2a32b9ff0f20703c4e188a581696779b8f435577d7ba height=2690 version=0x7bc5e5f1 log2_work=203.17549 tx=4129 date='2020-11-26 01:13:52' progress=0.007066 cache=10.2MiB(3934tx)
2021-02-16 22:34:54 UpdateTip: new best=27af40ba4053f6a80f7234166d22d21b7a0ec7b5232fbff77a00be1b4d4c765b height=2691 version=0x7bc5e5f1 log2_work=203.17549 tx=4131 date='2020-11-26 01:14:08' progress=0.007069 cache=10.3MiB(3936tx)
2021-02-16 22:34:54 UpdateTip: new best=dd97a04b31135300af5e35a1c83ba9c593c97e3fb63b4f8b985b406e29f76830 height=2692 version=0x7bc5e5f1 log2_work=203.17549 tx=4133 date='2020-11-26 01:14:24' progress=0.007073 cache=10.3MiB(3938tx)
2021-02-16 22:34:54 UpdateTip: new best=7c9c0ac76e2ed81d42187c763f244dcc0f925ff28569fc118c3990dced689f0a height=2693 version=0x7bc5e5f1 log2_work=203.17549 tx=4135 date='2020-11-26 01:14:40' progress=0.007076 cache=10.3MiB(3940tx)
```

**Comment by navbuilder** [comment]
A new build of 06efeaeb7271716d571e3200463427dc73468118 has completed succesfully!
Binaries available at https://build.nav.community/binaries/multiexp_optimisation

**Comment by navbuilder** [comment]
A new build of 47af90d481e4c72c142529979fce50d72a89f466 has completed succesfully!
Binaries available at https://build.nav.community/binaries/multiexp_optimisation

**Review by chasingkirkjufell — APPROVED** [review]
Tested gitian build on windows 10, 
average NAV to xNAV time dropped from 2.8 sec to 1.8 seconds
xNAV to xNAV dropped from 6.4 seconds to 3.3 seconds
xANAV to NAv dropped from 4.1 seconds to 3.4 seconds

**Review by mxaddict — APPROVED** [review]

**Comment by mxaddict** [comment]
@aguycalled I'll leave it up to you when to merge this PR

**Comment by mxaddict** [comment]
@aguycalled  I think we should merge this into master now since we are done with the hotfixes for xNAV?

**Comment by chasingkirkjufell** [comment]
Is gitian not building now with the new patches?

**Comment by mxaddict** [comment]
> Is gitian not building now with the new patches?

Not sure, @aguycalled will have to confirm

**Comment by navbuilder** [comment]
A new build of 557faa3137fde64bfb7a85cddad774e01113c6f2 has completed succesfully!
Binaries available at https://build.nav.community/binaries/multiexp_optimisation

**Comment by mxaddict** [comment]
@aguycalled  I think I know why you said this PR was faster when you were testing on OSX

I think it was cause of ASM support.

I think we can re-enable it for linux and osx clients, windows and arm I think fail to build on gitian with ASM, which is why we disabled it in the PR

**Comment by aguycalled** [comment]
we should enable it on linux/osx and test the performance.

what was the error for windows/arm?

**Comment by mxaddict** [comment]
> we should enable it on linux/osx and test the performance.
> 
> what was the error for windows/arm?

OSX cross compile is not working either.

I think it has to do with the link step, and also the CMakeList.txt will have to be modified to use the ASM files, currently it expects to build on native system.

**Comment by aguycalled** [comment]
gitian build x86 linux failing with last commit

```
...
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x778): undefined reference to `mcl_mcl_fp_addPre2L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x790): undefined reference to `mcl_mcl_fp_montRed1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x798): undefined reference to `mcl_mcl_fp_montNF1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7a0): undefined reference to `mcl_mcl_fp_mont1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7a8): undefined reference to `mcl_mcl_fp_subNF1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7b0): undefined reference to `mcl_mcl_fp_sub1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7b8): undefined reference to `mcl_mcl_fp_addNF1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7c0): undefined reference to `mcl_mcl_fp_add1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7c8): undefined reference to `mcl_mcl_fp_mulUnitPre1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7e0): undefined reference to `mcl_mcl_fp_shr1_1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7e8): undefined reference to `mcl_mcl_fp_subPre1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x7f0): undefined reference to `mcl_mcl_fp_addPre1Lbmi2'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x808): undefined reference to `mcl_mcl_fp_montRed1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x810): undefined reference to `mcl_mcl_fp_montNF1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x818): undefined reference to `mcl_mcl_fp_mont1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x820): undefined reference to `mcl_mcl_fp_subNF1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x828): undefined reference to `mcl_mcl_fp_sub1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x830): undefined reference to `mcl_mcl_fp_addNF1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x838): undefined reference to `mcl_mcl_fp_add1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x840): undefined reference to `mcl_mcl_fp_mulUnitPre1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x858): undefined reference to `mcl_mcl_fp_shr1_1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x860): undefined reference to `mcl_mcl_fp_subPre1L'
mcl/build/lib/libmcl.a(fp.cpp.o):(.data.rel.ro+0x868): undefined reference to `mcl_mcl_fp_addPre1L'
collect2: error: ld returned 1 exit status
Makefile:4411: recipe for target 'qt/navcoin-qt' failed
make[2]: *** [qt/navcoin-qt] Error 1
make[2]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-linux-gnu/src'
make[1]: *** [all-recursive] Error 1
Makefile:11093: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/ubuntu/build/navcoin-core/distsrc-x86_64-linux-gnu/src'
make: *** [all-recursive] Error 1
Makefile:718: recipe for target 'all-recursive' failed
```

**Comment by aguycalled** [comment]
merged upstream/master

**Comment by navbuilder** [comment]
A new build of 35be59f4757fa8dae915773b49093ea58b5a606f has completed succesfully!
Binaries available at https://build.nav.community/binaries/multiexp_optimisation

**Pull request merged**
