### PR TITLE
Remove NAVTech related code

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by aguycalled** [comment]
this is related to #465 and should be entirely removed

**Comment by mxaddict** [comment]
I see, can I work on #465?

**Comment by aguycalled** [comment]
sure, its done on zeroct branch already so it should be trivial. see https://github.com/skreener/navcoin-core/commit/dd49a78eef995ed758ef6d7c23f9e7b566529cea and https://github.com/skreener/navcoin-core/commit/4c9565a99ecf8d38bd6183ae131ad03525077675

**Comment by mxaddict** [comment]
Ahh, I guess no need to redo the work? Maybe just wait for the zeroct merge?

**Comment by aguycalled** [comment]
the zeroct branch might be completely deprecated and i don’t see a reason why the wallet should have non-working features like navtech any longer

**Comment by mxaddict** [comment]
Ok, I'll create a PR then.

**Comment by mxaddict** [comment]
Rather, I'm renaming this PR and I will push to this branch the changes to remove NavTech.

**Comment by mxaddict** [comment]
@aguycalled @proletesseract I'm not very confident with these changes, will need more scrutiny than usual :rofl:

**Comment by mxaddict** [comment]
The cfund related tests are failing, I'lll push the fixed code once ready.

I'll also update some of the RPC commands to replace `anon-destination` with `strdzeel`

**Comment by mxaddict** [comment]
Merged changes from #537 to make the test suite pass on travis

**Comment by mxaddict** [comment]
Rebased on master  branch

**Comment by mxaddict** [comment]
Closing as changes from this PR are merged into #557

**Pull request closed without merging**
