### PR TITLE
Updated images to try and fix #521

### LINKED ISSUE #521: OSX gitian build of master branch is funky looking
image

image

### PR DESCRIPTION
**Pull request by mxaddict**
Updated images to try and fix #521

### CODE REVIEW

**Comment by mxaddict** [comment]
@proletesseract could you do a gitian build of this PR and test the artifact bug for #521

**Comment by sherlockcoin** [comment]
My gitian just died. 🗡 Still fixing it.

**Comment by mxaddict** [comment]
@sherlockcoin if you want to use docker for gitian build, try this: https://github.com/navcoin/navcoin-core/pull/461#issuecomment-492199178

**Comment by proletesseract** [comment]
building with gitian for OSX now. will test later today once the build completes.

**Comment by mxaddict** [comment]
@proletesseract were you able to test the build?

I was able to test this on a friends mojave 10.14 and was working without the artifacting issue.

**Comment by mxaddict** [comment]
This is deprecated and the whole menu as been revamped in #557

**Comment by mxaddict** [comment]
Did not fix issue

**Pull request closed without merging**
