### PR TITLE
Added password prompt for CFund payment/proposal dialogs

### PR DESCRIPTION
**Pull request by francisjyap**
Added password prompt for CFund payment/proposal dialogs

This is for issue #457

### CODE REVIEW

**Comment by mxaddict** [comment]
utACK

**Comment by mxaddict** [comment]
Built on Ubuntu 18.04 (I'll do a testnet/devnet test for the functionality)

**Comment by aguycalled** [comment]
ACK tested on debian

**Comment by aguycalled** [comment]
@francisjyap please leave a comment in the original issue with a navcoin address for payment

**Comment by mxaddict** [comment]
@aguycalled the test seems to keep failing (Timeout) Any ideas how to get the travis build to work?

**Comment by aguycalled** [comment]
use travis_wait to extend the test job max execution time

**Comment by aguycalled** [comment]
Looks like it is not possible to extend the job duration to more than 50 min for public repositories using the free version of travis. Any alternatives different from reducing our test units?

**Comment by mxaddict** [comment]
> Looks like it is not possible to extend the job duration to more than 50 min for public repositories using the free version of travis. Any alternatives different from reducing our test units?

I think if we adjust testnet/devnet to so that the tests pass faster?

Like for example, we can have the static staking reward take only 150 (50 per step)  blocks instead of the current 300 (100 per step)

And I think the same can be done for cfund tests as well

**Pull request merged**
