### PR TITLE
[DAO] Fix for votes not being persisted

### PR DESCRIPTION
**Pull request by aguycalled**
This PR fixes a bug where votes were not correctly persisted in disk.

What to check: votes still show when wallet is restarted.

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 5ff1f8f542ae0135a1eda8887d7ba7c33955d46d has completed succesfully!
Binaries available at https://build.nav.community/binaries/persist-abs-vote

**Comment by mxaddict** [comment]
Will need to test all vote types? or just payment request and proposals?

**Comment by chasingkirkjufell** [comment]
> Will need to test all vote types? or just payment request and proposals?

Should be the same. The problem occurred to prodpeak where when he restarted a node, the abstain vote was removed. I could not replicate the issue so far and things are all looking good on my end.

**Comment by mxaddict** [comment]
> > Will need to test all vote types? or just payment request and proposals?
> 
> Should be the same. The problem occurred to prodpeak where when he restarted a node, the abstain vote was removed. I could not replicate the issue so far and things are all looking good on my end.

I see, I back read the convo in discord, looks like it might be an issue related to compiling/linking meaning it won't happen on all builds, might be good to have prodpeak check if he can still replicate this issue.

**Comment by mxaddict** [comment]
I could not replicate the issue on gitian builds, and could not replicate it on self built binary on Ubuntu 19.10

**Comment by mxaddict** [comment]
@aguycalled can we have prodpeak confirm this fixes the issue he had?

**Comment by proletesseract** [comment]
@aguycalled can you clarify how moving these declarations to the util.cpp/h  fixes the persistence issue?

**Comment by aguycalled** [comment]
@proletesseract variables were declared in dao.h but defined in util.cpp. libnavcoin_server_a_SOURCES includes dao.cpp/h but does not have util.cpp

**Pull request merged**
