### PR TITLE
Move nBits check to ContextualCheckBlock

### PR DESCRIPTION
**Pull request by aguycalled**
This PR moves the nBits check to ContextualCheckBlock.

### CODE REVIEW

**Comment by proletesseract** [comment]
Travis failed, re-running

**Comment by mxaddict** [comment]
utACK

**Comment by mxaddict** [comment]
@aguycalled I think `reindex.py` test fails on this branch

**Comment by aguycalled** [comment]
It passed locally
```
$ ./qa/pull-tester/rpc-tests.py reindex.py
WARNING: "import zmq" failed. Set ENABLE_ZMQ=0 or to run zmq tests, see dependency info in /qa/README.md.
.....................................................................................
reindex.py:
Initializing test directory /var/folders/qh/7_l8lmqx2sb5ncxgtzzyb51r0000gn/T/testjsjz8dit/0
Success
Success
Success
Success
Stopping nodes
Cleaning up
Tests successful

 
Pass: True, Duration: 43 s

TEST       | PASSED | DURATION

reindex.py | True   | 43 s

ALL        | True   | 43 s (accumulated)

Runtime: 43 s
```
Restarting travis

**Comment by mxaddict** [comment]
@aguycalled maybe you should merge master into this PR?

**Comment by mxaddict** [comment]
> testedACK

Tested on Ubuntu 18.04

**Comment by proletesseract** [comment]
building and testing now

**Comment by proletesseract** [comment]
Compiles and runs on ubuntu 18.04. 

- The --reindex flag gets stuck as best block 229 for me. Reconsidering the block doesn't get past it. 
- The --reindex-chainstate flag also gets stuck as best block 229 for me. Reconsidering the block does get past it though.
- Removing the data folder and syncing again gets past block 229.

Assuming this is just some localised problem and am still happy to merge, just thought it was worth documenting what happened in my tests.

Tests pass on travis so haven't run them locally.

**Pull request merged**
