### PR TITLE
Updated QT to version 5.12

### PR DESCRIPTION
**Pull request by mxaddict**
You will need to install `bison`  (`sudo apt install bison`) package on ubuntu to run depends build

### CODE REVIEW

**Comment by chasingkirkjufell** [comment]
i see it's still work in progress. was building it and then got an error. Will test it again when it's ready for review.

**Comment by mxaddict** [comment]
What was the error that you ran into?

**Comment by chasingkirkjufell** [comment]
local build is working with ubuntu 20.04 after installing bison. will try to test gitian soon

**Comment by mxaddict** [comment]
I found an issue with gitian symbol check build step.

I'll let you know once it's fixed.

**Comment by chasingkirkjufell** [comment]
> Made some progress with this recently, reopening for possible reviewal once I'm done

nice!

**Pull request closed without merging**
