### PR TITLE
Added a missing style for QWizard background color

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by mxaddict** [comment]
This fix is for the windows wizard for creating a cold staking address, it does not look as pretty as the linux/osx wizard with this PR, but it's atleast readable.

**Comment by mxaddict** [comment]
On this PR, this is what the UI will look like:

image

image

**Comment by navbuilder** [comment]
A new build of 9df2addfe9380a681065fdaafdc26cc0c3b83fa9 has completed succesfully!
Binaries available at https://build.nav.community/binaries/dark-mode-staking-dialog

**Review by chasingkirkjufell — APPROVED** [review]
not the prettiest but works, tested gitian build on windows 10

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
