### PR TITLE
OSX pink menu bug

### LINKED ISSUE #521: OSX gitian build of master branch is funky looking
image

image

### PR DESCRIPTION
**Pull request by proletesseract**
Fixes #521

Screen Shot 2019-08-20 at 9 01 14 PM

OSX build: https://builds.navcore.org/521-osx-png-bug

Gitian building the other OS binaries now to smoke test it doesn't break the layout on other operating systems.

### CODE REVIEW

**Comment by aguycalled** [comment]
image
image

**Comment by aguycalled** [comment]
The menu icons show with an appreciable lower resolution, but this can be a temporary valid solution until the whole redesign is finished. Would be interesting to confirm how it shows in other OS/resolutions.

**Comment by proletesseract** [comment]
@aguycalled yeah Juguelio reported the same, it works but its a bit blurry.

I have the other OS's compiled here now, so ill try to get people on discord to try it out:

https://builds.navcore.org/521-osx-png-bug/

**Comment by proletesseract** [comment]
unknown (5)

unknown (6)

**Comment by proletesseract** [comment]
and i agree, this is a quick interim fix before replacing the menu with @mxaddict's work. I could spend more time going down the pxmap approach but i dont think its worth the effort.

**Pull request merged**
