### PR TITLE
Fix to staking parameter "-mininputvalue"

### PR DESCRIPTION
**Pull request by R-Marino**
The nMinimumInputValue variable controls the minimum value
that can be selected for staking.
However, when the variable is defined, the parameter "-mininputvalue"
is not yet available. This makes the parameter irrelevant.

To correct this, the value of the variable is refreshed later, just
before it is actually used.

The correction does not seem to have any side effects, apart from
the improper use of the parameter itself.

Resolve: #585

### CODE REVIEW

**Comment by aguycalled** [comment]
utACK

**Comment by aguycalled** [comment]
test pass locally
```$ python3 qa/rpc-tests/staking_mininputvalue.py 
Initializing test directory /var/folders/qh/7_l8lmqx2sb5ncxgtzzyb51r0000gn/T/test6n2v3j7v/86803

BLK -14:          nd  nd              nd  nd              nd  nd      
BLK -13:      1001.0  small1      1980.0  large       1500.0  med__1  
BLK -12:      1001.0  small2      1980.0  large       1500.0  med__2  
BLK -11:      1001.0  small3      1980.0  large       1980.0  large   
BLK -10:      1001.0  small4      1980.0  large       1500.0  med__1  
BLK -9 :      1001.0  small5      1980.0  large       1500.0  med__2  
BLK -8 :      1500.0  med__1      1980.0  large       1980.0  large   
BLK -7 :      1500.0  med__2      1980.0  large       1500.0  med__1  
BLK -6 :          nd  nd              nd  nd              nd  nd      
blockcount:         47                  47                  47               
MinInputValue:    notset              1800.0              1500.0             
Stopping nodes
Cleaning up
Tests successful
```

**Comment by aguycalled** [comment]
@R-Marino please post a navcoin address for receiving the bounty once the pull request is merged

**Comment by mxaddict** [comment]
utACK

**Comment by mxaddict** [comment]
Compiling to test now

**Comment by mxaddict** [comment]
tested and working on Ubuntu 19.10

**Comment by mxaddict** [comment]
@proletesseract  @aguycalled this change seems small enough I'm merging into master

**Comment by aguycalled** [comment]
Paid ade284879efe7951bb025cbe0858251f63301eba0cd95856a619819cac7dd60a

**Pull request merged**
