### PR TITLE
[RPC][GUI] Fixed `netstakeweight` value in `getstakinginfo` rpc call

### LINKED ISSUE #539: getstakinginfo shows incorrect net stake weight
`getstakinginfo` shows a too low netstakeweight value
```
  "netstakeweight": 1954149692434622,
```
compared with the value of `navexplorer.com`'s api (total around 27M)
```
https://api.navexplorer.com/api/staking/blocks?blocks=10000
```

This leads to show a too big expected reward and too low expected time to get a reward.

The current methodology looks accurate, using the difficulty to try to guess the amount of coins staking, but is not giving sound numbers.

### PR DESCRIPTION
**Pull request by mxaddict**
closes #539

Fixed `netstakeweight` value in `getstakinginfo` rpc call

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of 1603d16e8e12407745b6b8b34a729a27b6e135b2 has completed succesfully!
Binaries available at https://build.nav.community/binaries/fixed-netstakeweight

**Comment by navbuilder** [comment]
A new build of 9c7cc20bb4befe8ccd737087fdf587c7fa7a1b8c has completed succesfully!
Binaries available at https://build.nav.community/binaries/fixed-netstakeweight

**Comment by mxaddict** [comment]
@aguycalled I've added the EDR to the GUI
Capture

**Comment by navbuilder** [comment]
A new build of 656034cec8cdb5cabc59061ed10b34360fb1d25a has completed succesfully!
Binaries available at https://build.nav.community/binaries/fixed-netstakeweight

**Comment by aguycalled** [comment]
should we also add the expected time for next reward?

**Comment by mxaddict** [comment]
> should we also add the expected time for next reward?

Up to you guys, I think it's confusing (Use might set there for the time it says, then realize it's an estimate and won't get the stake yet) 😄

**Comment by mxaddict** [comment]
> > should we also add the expected time for next reward?
> 
> Up to you guys, I think it's confusing (User might set there for the time it says, then realize it's an estimate and won't get the stake yet) 😄

I changed my mind, I think we should add it 🗡️ 
It will just be called ETA, so for sure they know it's not a fixed timer

**Comment by Xa5r** [comment]
As smaller the staker are, the more unstable will the ETA become.
But most stakers are small stakers and I would not like to get them all frustrated.
I remember Users became angry because the old ETA wasn't right.

**Comment by mxaddict** [comment]
> As smaller the staker are, the more unstable will the ETA become.
> But most stakers are small stakers and I would not like to get them all frustrated.
> I remember Users became angry because the old ETA wasn't right.

I think we should discuss this a bit more.

**Comment by aguycalled** [comment]
maybe we can hide the information by default and let users who want to see it to activate it. then after some time we can decide based of users feedback

**Comment by Xa5r** [comment]
Sounds good

**Comment by navbuilder** [comment]
A new build of 21c9794c9a157d7c6eaff585bd1cadc5b10ea650 has completed succesfully!
Binaries available at https://build.nav.community/binaries/fixed-netstakeweight

**Pull request merged**
