### PR TITLE
Updated libgmp package in depends to work with WSL builds on windows

### PR DESCRIPTION
**Pull request by mxaddict**
Requires #891
NOTE: Just need to make sure that gitian build on Ubuntu/Gitian still work with this change

### CODE REVIEW

**Comment by mxaddict** [comment]
Closing this as I think I found a less intrusive method of getting WSL to work

**Comment by mxaddict** [comment]
Re-opening as the fix for removing the WSL path values only works for osx and linux build on WSL, ironically windows builds on WSL were still failing.

**Comment by mxaddict** [comment]
Just did a WSL build for mingw32 and ran the navcoin-qt.exe from WSL CLI and worked good:
image

**Comment by mxaddict** [comment]
Waiting on gitian build to see if this breaks anything in the build process.

**Comment by navbuilder** [comment]
A new build of 28dea21a3c464508d958785f81c5fca0745fe502 has completed succesfully!
Binaries available at https://build.nav.community/binaries/fix-libgmp-depends-for-wsl

**Review by aguycalled — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]

**Pull request merged**
