### PR TITLE
Upstream changes for depends build Makefile and funcs.mk

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of dfc043b1ad310fbd6ae223cef3d314d9dfd37405 has completed succesfully!
Binaries available at https://build.nav.community/binaries/upstream-depends-makefile-funcs.mk

**Comment by mxaddict** [comment]
@aguycalled  @chasingkirkjufell Gitian build for this PR is ready let me know if you find any issues with them.

**Comment by chasingkirkjufell** [comment]
yep, will try to test it soon

**Review by aguycalled — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]
tested a local ubuntu 20.04 build

**Pull request merged**
