### PR TITLE
Fix for REAL prog wrapper issue on gitian

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by navbuilder** [comment]
A new build of d302a82777b747e700ba39071e32d294dbc3df13 has completed succesfully!
Binaries available at https://build.nav.community/binaries/mxaddict:fix-for-real-issue

**Comment by navbuilder** [comment]
A new build of a4a98ec7aca280758305621a631250786807de37 has completed succesfully!
Binaries available at https://build.nav.community/binaries/mxaddict:fix-for-real-issue

**Comment by navbuilder** [comment]
A new build of ee040429288a6cf8f2ca18466147afaeeebf7d5c has completed succesfully!
Binaries available at https://build.nav.community/binaries/mxaddict:fix-for-real-issue

**Comment by mxaddict** [comment]
@aguycalled  @chasingkirkjufell I think this PR is ready to test, this should fix the master build issues, and incorporates some upstream changes to the gitian files.

**Review by aguycalled — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]

**Pull request merged**
