### PR TITLE
Add community fund donate button to send page

### PR DESCRIPTION
**Pull request by dy5es41**

### CODE REVIEW

**Comment by dy5es41** [comment]
travis failing due to non deterministic test (ran 10 times on my machine and it seems to work). coldstaking_spending.py
`JSONRPC error: Error: This transaction requires a transaction fee of at least 0.0028851 because of its amount, complexity, or use of recently received funds!`
current minimum fee in the test is set as:
`MIN_COLDSTAKING_SENDING_FEE = 0.0028850`
which is one below the failing transaction fee. will have to looking into how our transaction fees are calculated.

**Comment by aguycalled** [comment]
image
The amount text box looks black in my system.

**Comment by aguycalled** [comment]
the issue of the text field is related to  #403

**Comment by matt-auckland** [comment]
@aguycalled how do you feel about this PR? Do we want to fix this dark mode issue before merging?

**Comment by craigmacgregor** [comment]
Need to fix this box on dark mode.

Need to evaluate / move the checkbox (discuss with @kakax114)

**Comment by dy5es41** [comment]
Carter and I have decided to move the option for sending to the community fund. It will instead now be located under the community fund drop down. I am closing this pull so I can rewrite.
image

**Comment by aguycalled** [comment]
src/qt/NavCoin4.creator.user should not be included in the pull request

**Comment by dy5es41** [comment]
we decided against it as we wanted to save having to remake the entire sendcoinsentry/sendcoinsdialog ui and it's implementation. Also allows for specific inputs to be spent to community fund

**Comment by aguycalled** [comment]
i'm not sure if it is worth it to overcomplicate the send interface

**Comment by aguycalled** [comment]
i'd alternatively suggest adding a button in the address book dialog

**Comment by craigmacgregor** [comment]
@dy5es41 We need to cut the RC for 4.5.2 today. Is this going to be ready? Jump on discord to discuss if you are able.

**Comment by aguycalled** [comment]
should this be closed?

**Pull request closed without merging**
