### PR TITLE
Add codesign to gitian

### PR DESCRIPTION
**Pull request by aguycalled**

### CODE REVIEW

**Comment by mxaddict** [comment]
Nice, this is upstream changes?

**Comment by mxaddict** [comment]
Changes look like they make sense, I will test when I get home.

**Comment by mxaddict** [comment]
@aguycalled can you send me a sample `signature-osx.tar.gz`

**Review by mxaddict — APPROVED** [review]

**Comment by chasingkirkjufell** [comment]
Is the build bot running for this PR?

**Comment by navbuilder** [comment]
A new build of a8c7b38f356fb708a61958394697f9666c92c46d has completed succesfully!
Binaries available at https://build.nav.community/binaries/codesign

**Comment by aguycalled** [comment]
[signature.tar.gz](https://github.com/navcoin/navcoin-core/files/5801201/signature.tar.gz)

**Comment by aguycalled** [comment]
got it working
https://build.nav.community/binaries/codesign/navcoin-osx-signed.dmg

**Review by mxaddict — APPROVED** [review]
Additional changes look good, especially the documentation 👍

**Review by chasingkirkjufell — APPROVED** [review]

**Pull request merged**
