### PR TITLE
Updates to make the wallet.py and stakeimmaturebalance.py test more reliable

### PR DESCRIPTION
**Pull request by mxaddict**
I saw these test was failing intermittently, I think this change will fix that.

### CODE REVIEW

**Comment by aguycalled** [comment]
utACK

**Comment by aguycalled** [comment]
wallet.py test still fails

**Comment by mxaddict** [comment]
@aguycalled I've updated the commit

**Comment by mxaddict** [comment]
I updated the `stakeimmaturebalance.py` test as well

**Comment by aguycalled** [comment]
restarting travis build to check it still passes

**Comment by mxaddict** [comment]
The build failed, but due to memonic test, I've restarted the failed test.

**Comment by navbuilder** [comment]
A new build of 62f6bb9de1f3d1fa3f70e78f866a4829042964f6 has completed succesfully!
Binaries available at https://build.nav.community/binaries/update-wallet-rpc-test

**Comment by mxaddict** [comment]
@proletesseract  @chasingkirkjufell could you spare a moment to review the changes to the py tests on this PR?

**Pull request merged**
