### PR TITLE
Added release notes

### PR DESCRIPTION
**Pull request by mxaddict**
Added a release notes file with list of PRs merged into master

### CODE REVIEW

**Comment by aguycalled** [comment]
why temp.txt?

**Comment by mxaddict** [comment]
> why temp.txt?

I removed it, got committed by mistake.

**Comment by chasingkirkjufell** [comment]
#614 #566 #561 #546 are missing I think?

**Comment by mxaddict** [comment]
> #614 #566 #561 #546 are missing I think?

I've added those now.

**Comment by mxaddict** [comment]
Added #527 to the notes

**Pull request merged**
