### PR TITLE
Check stake spent

### PR DESCRIPTION
**Pull request by aguycalled**
This PR introduces checks to verify if a coinstake provides a spent output as input on a forked chain. Took this from PIVX.

Depends on aguycalled/functional-tests for the test.

### CODE REVIEW

**Comment by mxaddict** [comment]
utACK, still building

**Comment by mxaddict** [comment]
@aguycalled `cfund-paymentrequest-state-reorg.py` fails on this branch

**Comment by navbuilder** [comment]
A new build of 9cb4ebd042817e8d54c509d6f18ec8256d87a2e2 has completed succesfully!
Binaries available at https://build.nav.community/binaries/check-stake-spent

**Comment by mxaddict** [comment]
@aguycalled  is this PR still relevant?

**Pull request closed without merging**
