### PR TITLE
Replaced all BOOST_FOREACH calls with new for() syntax (c++11)

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by aguycalled** [comment]
should we add a linter to check there's no regression on this?

**Comment by mxaddict** [comment]
> should we add a linter to check there's no regression on this?

Make sense, but I think we need to finish the `functional-tests` branch changes before adding the linter?

**Comment by proletesseract** [comment]
Resolved merge conflict after merging PR #524, waiting on travis.

builds and runs on ubuntu 18.04

**Comment by mxaddict** [comment]
Rebasing now, will push when done.

**Comment by mxaddict** [comment]
> Rebasing now, will push when done.

Rebase pushed

**Comment by mxaddict** [comment]
Merged changes from master

**Comment by mxaddict** [comment]
Rebased PR on updated master branch.

**Pull request merged**
