### PR TITLE
Added skip dialog for seed backup step

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by chasingkirkjufell** [comment]
Ubuntu 18.10 Local Build
- [x] Skip mnemonic confirmation
- [x] Incomplete seed verification returns warning message and return to verification page
- [x] Complete seed verification boots up wallet

Will approve it later after finish testing on windows.

**Comment by navbuilder** [comment]
A new build of 5fb05b4d5520cdf714b093829a0dde42d30a02a1 has completed succesfully!
Binaries available at https://build.nav.community/binaries/mnemonic-import-gui-changes

**Comment by navbuilder** [comment]
A new build of c409bf7e5802d16805dba4a485049a3262a8eeab has completed succesfully!
Binaries available at https://build.nav.community/binaries/mnemonic-import-gui-changes

**Comment by aguycalled** [comment]
tested osx gitian

**Pull request merged**
